//! HTTP requests and host transport errors.

/// An HTTP method that the host must execute.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpMethod {
    /// An HTTP GET request.
    Get,
    /// An HTTP POST request.
    Post,
}

/// Correlation identity generated by Rust. Hosts can use it to bind their
/// native cancellation bookkeeping, but must not assign semantic meaning to
/// the numeric value.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Record,
)]
#[serde(rename_all = "camelCase")]
pub struct HttpRequestId {
    /// An opaque numeric value allocated by this client instance.
    pub value: u64,
}

/// One HTTP header name and value.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpHeader {
    /// The header name.
    pub name: String,
    /// The header value.
    pub value: String,
}

/// A complete HTTP request for the embedding language.
///
/// The host can add its Toncenter credential according to the actual request
/// URL and its local security policy. Redirects are forbidden.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpRequest {
    /// The identifier used for host cancellation.
    pub id: HttpRequestId,
    /// The request method.
    pub method: HttpMethod,
    /// The complete HTTPS request URL.
    pub url: String,
    /// The public request headers. Credential material is not present here.
    pub headers: Vec<HttpHeader>,
    /// The request body. GET requests use an empty body.
    pub body: Vec<u8>,
    /// End-to-end request timeout, in milliseconds.
    ///
    /// The host must enforce this deadline across connection setup, response
    /// headers, and response-body reads. Expiry is reported as
    /// [`HttpHostErrorKind::Timeout`].
    pub timeout_ms: u64,
}

/// The complete HTTP response returned by the host.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpResponse {
    /// The HTTP status code.
    pub status: u16,
    /// The response headers accepted by the host.
    pub headers: Vec<HttpHeader>,
    /// The response body accepted by the host.
    pub body: Vec<u8>,
    /// The final response URL reported by the host. It must equal the request URL
    /// because the engine does not permit redirects.
    pub final_url: String,
}

/// Classifies a failure reported by the HTTP host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostErrorKind {
    /// No network connection is available.
    Offline,
    /// The request exceeded a host timeout.
    Timeout,
    /// An established connection ended before completion.
    ConnectionLost,
    /// DNS resolution failed.
    Dns,
    /// TLS negotiation or certificate validation failed.
    Tls,
    /// The request violated a host security policy.
    PolicyViolation,
    /// The response exceeded a limit imposed by the host.
    ResponseTooLarge,
    /// The host cancelled the request.
    Cancelled,
    /// The failure does not match another kind.
    Other,
}

/// An HTTP failure returned by [`crate::WalletHttpHost`].
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[uniffi::export(Display)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostError {
    /// Reports a classified host failure with a safe diagnostic message.
    #[error("HTTP host failure ({kind:?}): {diagnostic}")]
    Failed {
        /// The stable failure classification.
        kind: HttpHostErrorKind,
        /// A developer-facing message without secrets or credential values.
        diagnostic: String,
    },
}
