use std::fs;
use std::path::Path;
use std::process::Command;

use anyhow::{Context, Result, bail};
use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;

use crate::files::require_file;
use crate::paths::repository_root;
use crate::process::run_command;

pub(crate) fn generate_wasm(check: bool) -> Result<()> {
    let root = repository_root()?;
    let output = root.join("bindings/wasm");
    let temporary = tempfile::Builder::new()
        .prefix("wallet-engine-wasm-bindings-")
        .tempdir()
        .context("failed to create temporary WASM bindings directory")?;
    let generated = temporary.path().join("generated");

    let mut command = Command::new("wasm-pack");
    command
        .current_dir(&root)
        .env("CARGO_TARGET_DIR", root.join("target/wasm-bindings"))
        .arg("build")
        .arg(root.join("wasm-bindings"))
        .arg("--target")
        .arg("web")
        .arg("--profile")
        .arg("release-size")
        .arg("--no-opt")
        .arg("--out-dir")
        .arg(&generated)
        .arg("--out-name")
        .arg("wallet_engine");
    run_command(&mut command)?;

    optimize_wasm(&generated)?;
    disable_default_wasm_fetch(&generated)?;
    embed_wasm(&generated)?;
    validate_wasm(&generated)?;
    if !check {
        replace_directory(&generated, &output)?;
    }
    Ok(())
}

fn optimize_wasm(generated: &Path) -> Result<()> {
    let input = generated.join("wallet_engine_bg.wasm");
    let output = generated.join("wallet_engine_bg.optimized.wasm");
    let mut command = Command::new("wasm-opt");
    command
        .arg(&input)
        .arg("-Oz")
        .arg("--enable-bulk-memory")
        .arg("--enable-bulk-memory-opt")
        .arg("--enable-nontrapping-float-to-int")
        .arg("-o")
        .arg(&output);
    run_command(&mut command)?;
    fs::rename(&output, &input).context("failed to install optimized WASM module")
}

fn disable_default_wasm_fetch(generated: &Path) -> Result<()> {
    let glue_path = generated.join("wallet_engine.js");
    let glue = fs::read_to_string(&glue_path)
        .with_context(|| format!("failed to read {}", glue_path.display()))?;
    let default_fetch = concat!(
        "    if (module_or_path === undefined) {\n",
        "        module_or_path = new URL('wallet_engine_bg.wasm', import.meta.url);\n",
        "    }",
    );
    if !glue.contains(default_fetch) {
        bail!("generated WASM glue has an unexpected default loader")
    }
    let embedded_only = concat!(
        "    if (module_or_path === undefined) {\n",
        "        throw new Error('Wallet Engine WASM bytes are required');\n",
        "    }",
    );
    fs::write(&glue_path, glue.replacen(default_fetch, embedded_only, 1))
        .context("failed to disable the generated WASM fetch fallback")
}

fn validate_wasm(generated: &Path) -> Result<()> {
    for filename in [
        "package.json",
        "wallet_engine.js",
        "wallet_engine.d.ts",
        "wallet_engine_bg.wasm",
        "wallet_engine_bg.wasm.d.ts",
        "wallet_engine_bg_base64.ts",
    ] {
        require_file(&generated.join(filename))?;
    }

    let declarations = fs::read_to_string(generated.join("wallet_engine.d.ts"))
        .context("failed to read generated WASM declarations")?;
    if declarations.contains("export class WalletClient")
        && declarations.contains("export class WalletLifecycle")
        && declarations.contains("export interface WalletHttpHost")
        && declarations.contains("export interface WalletPlatformHost")
    {
        Ok(())
    } else {
        bail!("generated WASM package is missing the expected public API")
    }
}

fn embed_wasm(generated: &Path) -> Result<()> {
    let wasm_path = generated.join("wallet_engine_bg.wasm");
    let wasm =
        fs::read(&wasm_path).with_context(|| format!("failed to read {}", wasm_path.display()))?;
    let encoded = STANDARD.encode(wasm);
    let module = format!(
        "// Generated by `cargo xtask bindings wasm`. Do not edit.\n\
         export const walletEngineWasmBase64: string = \"{encoded}\"\n"
    );
    fs::write(generated.join("wallet_engine_bg_base64.ts"), module)
        .context("failed to write embedded WASM TypeScript module")
}

fn replace_directory(source: &Path, destination: &Path) -> Result<()> {
    if destination.exists() {
        fs::remove_dir_all(destination).with_context(|| {
            format!("failed to remove stale directory {}", destination.display())
        })?;
    }
    copy_directory(source, destination)
}

fn copy_directory(source: &Path, destination: &Path) -> Result<()> {
    fs::create_dir_all(destination)
        .with_context(|| format!("failed to create {}", destination.display()))?;
    for entry in
        fs::read_dir(source).with_context(|| format!("failed to read {}", source.display()))?
    {
        let entry = entry.context("failed to read generated WASM directory entry")?;
        let source_path = entry.path();
        let destination_path = destination.join(entry.file_name());
        if entry
            .file_type()
            .context("failed to inspect generated WASM entry")?
            .is_dir()
        {
            copy_directory(&source_path, &destination_path)?;
        } else {
            fs::copy(&source_path, &destination_path).with_context(|| {
                format!(
                    "failed to copy {} to {}",
                    source_path.display(),
                    destination_path.display()
                )
            })?;
        }
    }
    Ok(())
}
