use crate::model::BindingsModel;

pub(super) fn render(model: &BindingsModel) -> String {
    format!(
        r#"#ifndef WALLET_ENGINE_H
#define WALLET_ENGINE_H

/* Generated by wallet-engine-c-bindgen. Do not edit. */

#include <stdint.h>

#if defined(_WIN32)
#  if defined(WALLET_ENGINE_BUILD)
#    define WALLET_ENGINE_API __declspec(dllexport)
#  else
#    define WALLET_ENGINE_API __declspec(dllimport)
#  endif
#elif defined(__GNUC__)
#  define WALLET_ENGINE_API __attribute__((visibility("default")))
#else
#  define WALLET_ENGINE_API
#endif

/* ABI version zero marks this generated facade as experimental. */
#define WALLET_ENGINE_ABI_VERSION {abi_version}u

/* UniFFI contract version read from the compiled Rust component metadata. */
#define WALLET_ENGINE_UNIFFI_CONTRACT_VERSION {uniffi_contract_version}u

WALLET_ENGINE_API uint32_t wallet_engine_abi_version(void);

WALLET_ENGINE_API uint32_t wallet_engine_uniffi_contract_version(void);

#endif /* WALLET_ENGINE_H */
"#,
        abi_version = model.abi_version(),
        uniffi_contract_version = model.uniffi_contract_version(),
    )
}

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use uniffi_bindgen::ComponentInterface;

    use super::render;
    use crate::model::BindingsModel;

    #[test]
    fn renders_a_self_contained_experimental_header() -> Result<()> {
        let component = ComponentInterface::new("wallet_engine");
        let model = BindingsModel::from_components(&[component])?;
        let header = render(&model);

        assert!(header.starts_with("#ifndef WALLET_ENGINE_H\n"));
        assert!(header.contains("#define WALLET_ENGINE_ABI_VERSION 0u\n"));
        assert!(header.contains("wallet_engine_abi_version(void);"));
        assert!(header.ends_with("#endif /* WALLET_ENGINE_H */\n"));
        Ok(())
    }
}
