use crate::model::BindingsModel;
use crate::type_map::BuiltinType;

pub(super) fn render(model: &BindingsModel) -> String {
    let mut header = format!(
        r#"#ifndef WALLET_ENGINE_H
#define WALLET_ENGINE_H

/* Generated by wallet-engine-c-bindgen. Do not edit. */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32)
#  if defined(WALLET_ENGINE_BUILD)
#    define WALLET_ENGINE_API __declspec(dllexport)
#  else
#    define WALLET_ENGINE_API __declspec(dllimport)
#  endif
#elif defined(__GNUC__)
#  define WALLET_ENGINE_API __attribute__((visibility("default")))
#else
#  define WALLET_ENGINE_API
#endif

/* ABI version zero marks this generated facade as experimental. */
#define WALLET_ENGINE_ABI_VERSION {abi_version}u

/* UniFFI contract version read from the compiled Rust component metadata. */
#define WALLET_ENGINE_UNIFFI_CONTRACT_VERSION {uniffi_contract_version}u
"#,
        abi_version = model.abi_version(),
        uniffi_contract_version = model.uniffi_contract_version(),
    );

    if model.has_builtin_type(BuiltinType::String) {
        header.push_str(
            r"
/*
 * A borrowed, non-NUL-terminated UTF-8 string.
 *
 * `data` may be NULL only when `len` is zero. The bytes remain owned by the
 * caller and must stay readable for the documented lifetime of the view.
 */
typedef struct WalletEngineStringView {
    const char *data;
    size_t len;
} WalletEngineStringView;
",
        );
    }

    if model.has_builtin_type(BuiltinType::Bytes) {
        header.push_str(
            r"
/*
 * A borrowed sequence of bytes.
 *
 * `data` may be NULL only when `len` is zero. The bytes remain owned by the
 * caller and must stay readable for the documented lifetime of the view.
 */
typedef struct WalletEngineBytesView {
    const uint8_t *data;
    size_t len;
} WalletEngineBytesView;
",
        );
    }

    header.push_str(
        r"
WALLET_ENGINE_API uint32_t wallet_engine_abi_version(void);

WALLET_ENGINE_API uint32_t wallet_engine_uniffi_contract_version(void);

#endif /* WALLET_ENGINE_H */
",
    );
    header
}

#[cfg(test)]
mod tests {
    use anyhow::Result;
    use uniffi_bindgen::ComponentInterface;

    use super::render;
    use crate::model::BindingsModel;

    #[test]
    fn renders_a_self_contained_experimental_header() -> Result<()> {
        let component = ComponentInterface::new("wallet_engine");
        let model = BindingsModel::from_components(&[component])?;
        let header = render(&model);

        assert!(header.starts_with("#ifndef WALLET_ENGINE_H\n"));
        assert!(header.contains("#define WALLET_ENGINE_ABI_VERSION 0u\n"));
        assert!(header.contains("wallet_engine_abi_version(void);"));
        assert!(header.ends_with("#endif /* WALLET_ENGINE_H */\n"));
        Ok(())
    }

    #[test]
    fn renders_borrowed_string_and_byte_views_when_used() -> Result<()> {
        let component = ComponentInterface::from_webidl(
            r"
            namespace wallet_engine {};

            dictionary Example {
                string name;
                bytes payload;
            };
            ",
            "wallet_engine",
        )?;
        let model = BindingsModel::from_components(&[component])?;
        let header = render(&model);

        assert!(header.contains("typedef struct WalletEngineStringView"));
        assert!(header.contains("typedef struct WalletEngineBytesView"));
        Ok(())
    }
}
