//! Wallet lifecycle, key derivation, and transfer construction.
//!
//! The public API creates and imports wallets while the host stores recovery
//! words. Private submodules derive wallet keys and build signed transfers.

pub(crate) mod crypto;
pub(crate) mod encrypted_comment;
pub(crate) mod mnemonic;
pub(crate) mod nft_transfer;
pub(crate) mod send;
pub(crate) mod slip_0010;
pub(crate) mod transfer;

use std::sync::Arc;

use ed25519_dalek::{Signer as _, SigningKey};
use ton::ton_core::{traits::tlb::TLB as _, types::TonAddress};
use ton_connect_core::{RawAccountAddress, ton_proof_signing_hash};

use self::crypto::{
    SensitiveMnemonic, derive_wallet, derive_wallet_public_state, generate_mnemonic,
};
use crate::TonAddressString;
use crate::domain::{
    Network, ProtectedSecretHostError, ProtectedSecretHostErrorKind, ProtectedSecretRead,
    ProtectedSecretRef, ProtectedSecretStore, SecretAccessReason, bounded_diagnostic,
};
use crate::engine::WalletPlatformHost;
use crate::types::TonAddressExt as _;

const MAX_RECORD_ID_BYTES: usize = 128;

/// Public, persistable wallet metadata. Recovery words never belong here.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletDescriptor {
    /// The stable application record identifier.
    pub record_id: String,
    /// The derived friendly non-bounceable TON address.
    pub address: TonAddressString,
    /// The raw 32-byte Ed25519 anchor public key of the rotation mnemonic.
    ///
    /// The anchor key determines the wallet account address and never
    /// changes, so this is safe to persist. It lets the engine emulate a
    /// first deployment before it asks the host to unlock the recovery
    /// phrase.
    pub public_key: Vec<u8>,
    /// The network used for derivation and future operations.
    pub network: Network,
    /// The host protected-storage reference for the mnemonic.
    pub secret_ref: ProtectedSecretRef,
}

/// Requests an address-bound off-chain TON Connect ownership proof signature.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectProofSignRequest {
    /// Wallet whose protected key must sign the proof.
    pub descriptor: WalletDescriptor,
    /// Exact manifest domain shown to and approved by the user.
    pub domain: String,
    /// Unix signing timestamp in seconds.
    pub timestamp: u64,
    /// Exact dApp challenge from the `ton_proof` connect item.
    pub payload: String,
}

/// Ed25519 result of an authorized TON Connect ownership proof.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectProofSignature {
    /// Exact 64-byte Ed25519 signature.
    pub signature: Vec<u8>,
}

/// Public account material sent in a TON Connect `ton_addr` reply.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectAccountInfo {
    /// Canonical raw TON address (`workchain:hex`).
    pub address: String,
    /// TON network global ID encoded as a decimal string.
    pub network: String,
    /// Canonical standard-base64 wallet `StateInit` `BoC`.
    pub wallet_state_init: String,
    /// Raw 32-byte Ed25519 public key.
    pub public_key: Vec<u8>,
}

/// Requests generation of a new wallet account.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreateWalletRequest {
    /// Stable application identity, normally a UUID generated by the host.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
}

/// A secret-bearing one-shot command. It must never be persisted or logged.
///
/// The words cross FFI because the user enters them. Rust validates and derives
/// the wallet. The host only provides protected storage.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ImportWalletRequest {
    /// The stable application record identifier for the imported wallet.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
    /// Lowercase English words of a rotation mnemonic (TEP-0003 section 3.3).
    ///
    /// Pass the phrase exactly as the user recorded it: 12 words for a wallet
    /// whose key was never rotated, or 24 words - two independently
    /// checksummed BIP-39 halves - after rotation. The engine expands the
    /// 12-word form itself; never duplicate the words in the application.
    pub recovery_words: Vec<String>,
}

/// A deliberately one-shot presentation value, not wallet state.
///
/// The UI must discard this value as soon as the recovery-phrase screen is
/// dismissed. Neither `WalletDescriptor` nor `WalletSnapshot` contains it.
///
/// A newly created wallet has a 12-word phrase; the phrase becomes 24 words
/// when the wallet's key is rotated.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryPhrase {
    /// The recovery words in order, separated by one ASCII space.
    ///
    /// Keeping the phrase in one allocation avoids separately allocated
    /// secret strings at the FFI boundary. Split it only while presenting
    /// individual words, then release those temporary views.
    pub phrase: String,
}

/// Result of creating a wallet.
///
/// The descriptor is safe to persist. The recovery phrase is transient and
/// exists only so the UI can show it once.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreatedWallet {
    /// Metadata that the application must persist.
    pub descriptor: WalletDescriptor,
    /// A transient phrase that the application can present once.
    pub recovery_phrase: RecoveryPhrase,
}

/// A wallet creation, import, secret, or derivation failure.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[uniffi::export(Display)]
#[serde(rename_all = "camelCase")]
pub enum WalletLifecycleError {
    /// The record ID is empty, too long, or contains unsupported characters.
    #[error("invalid wallet record identifier")]
    InvalidRecordId,
    /// The recovery phrase is not a valid 12- or 24-word Rotation mnemonic.
    #[error("invalid recovery phrase")]
    InvalidRecoveryPhrase,
    /// Rust cannot construct the requested wallet address.
    #[error("wallet address derivation failed")]
    AddressDerivationFailed,
    /// The TON Connect proof fields or signing key are invalid.
    #[error("TON Connect ownership proof signing failed")]
    TonConnectSigningFailed,
    /// The protected mnemonic derives a different address from the descriptor.
    #[error("protected recovery phrase does not belong to this wallet")]
    SecretWalletMismatch,
    /// The host reported a protected-storage failure.
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    ProtectedSecretHost {
        /// The stable host failure classification.
        kind: ProtectedSecretHostErrorKind,
        /// A sanitized developer-facing diagnostic.
        diagnostic: String,
    },
}

impl From<ProtectedSecretHostError> for WalletLifecycleError {
    fn from(value: ProtectedSecretHostError) -> Self {
        match value {
            ProtectedSecretHostError::Failed { kind, diagnostic } => Self::ProtectedSecretHost {
                kind,
                diagnostic: bounded_diagnostic(diagnostic),
            },
        }
    }
}

/// Coordinates wallet creation and recovery-phrase access.
///
/// It intentionally has no stream, refresh, reconciliation, or journal API.
/// The embedding application owns public wallet metadata. This object owns the
/// boundary between Rust key derivation and protected storage.
#[derive(uniffi::Object)]
pub struct WalletLifecycle {
    platform_host: Arc<dyn WalletPlatformHost>,
}

#[uniffi::export]
impl WalletLifecycle {
    #[uniffi::constructor]
    /// Creates a lifecycle service backed by `platform_host`.
    ///
    /// The application can share this object across wallet operations. The
    /// application remains responsible for the lifetime of host resources.
    pub fn new(platform_host: Arc<dyn WalletPlatformHost>) -> Arc<Self> {
        Arc::new(Self { platform_host })
    }

    /// Generates the initial 12-word recovery phrase, derives its wallet
    /// account, and stores the phrase.
    ///
    /// A new wallet starts before its one-time key rotation, so its signing
    /// key equals its anchor key and the user records a single 12-word half.
    ///
    /// Persist `descriptor` after this method succeeds. Present the recovery
    /// phrase once, then release all application copies of it.
    pub async fn create_wallet(
        &self,
        request: CreateWalletRequest,
    ) -> Result<CreatedWallet, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret =
            generate_mnemonic().map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        let recovery_phrase = recovery_phrase(&secret)?;

        Ok(CreatedWallet {
            descriptor,
            recovery_phrase,
        })
    }

    /// Validates and imports an entered mnemonic as a wallet account.
    ///
    /// The host stores the phrase with a user-presence requirement. The result
    /// contains only metadata that is safe for normal application storage.
    pub async fn import_wallet(
        &self,
        request: ImportWalletRequest,
    ) -> Result<WalletDescriptor, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret = SensitiveMnemonic::from_words(request.recovery_words)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        Ok(descriptor)
    }

    /// Authorizes secret access and returns a verified recovery phrase.
    ///
    /// Rust derives an address from the returned secret and compares it with
    /// the descriptor. Release the returned phrase after the UI closes.
    pub async fn reveal_recovery_phrase(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<RecoveryPhrase, WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: descriptor.secret_ref.clone(),
                reason: SecretAccessReason::RevealRecoveryPhrase,
                prompt: "Authenticate to reveal this wallet's recovery phrase".to_owned(),
            })
            .await?;

        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let actual = derive_address(descriptor.network, &secret)?;
        let expected = descriptor.address.as_address();

        if &actual != expected {
            return Err(WalletLifecycleError::SecretWalletMismatch);
        }

        recovery_phrase(&secret)
    }

    /// Deletes the protected secret for a wallet descriptor.
    ///
    /// This method does not delete application metadata or journal records.
    /// Delete the stored descriptor only after this method succeeds.
    pub async fn delete_wallet(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<(), WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        self.platform_host
            .delete_protected_secret(descriptor.secret_ref)
            .await
            .map_err(Into::into)
    }

    /// Authorizes the protected key and signs a TON Connect ownership proof.
    ///
    /// Rust constructs the protocol digest itself. The caller cannot use this
    /// API as a generic Ed25519 signing oracle, and no mnemonic or private-key
    /// bytes cross the API boundary.
    pub async fn sign_ton_connect_proof(
        &self,
        request: TonConnectProofSignRequest,
    ) -> Result<TonConnectProofSignature, WalletLifecycleError> {
        validate_descriptor(&request.descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: request.descriptor.secret_ref.clone(),
                reason: SecretAccessReason::SignTonConnectProof,
                prompt: format!(
                    "Authenticate to sign in to {} with TON Connect",
                    request.domain
                ),
            })
            .await?;
        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

        sign_ton_connect_proof(&secret, &request)
    }

    /// Derives the public TON Connect account reply without reading a secret.
    pub fn ton_connect_account(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<TonConnectAccountInfo, WalletLifecycleError> {
        derive_ton_connect_account(descriptor)
    }
}

impl WalletLifecycle {
    async fn store(
        &self,
        secret_ref: &ProtectedSecretRef,
        bytes: &[u8],
    ) -> Result<(), WalletLifecycleError> {
        self.platform_host
            .store_protected_secret(ProtectedSecretStore {
                secret_ref: secret_ref.clone(),
                bytes: bytes.to_vec(),
                // This is an access-control requirement for subsequent reads,
                // not a request to prompt while creating the item.
                require_user_presence: true,
            })
            .await
            .map_err(Into::into)
    }
}

fn derive_descriptor(
    record_id: &str,
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<WalletDescriptor, WalletLifecycleError> {
    let secret_ref = secret_ref_for(record_id);

    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
    let wallet = derive_wallet(phrase, network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(WalletDescriptor {
        record_id: record_id.to_owned(),
        address: TonAddressString::try_from(wallet.address.to_user_friendly(network))
            .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?,
        public_key: wallet.key_pair.public_key.to_vec(),
        network,
        secret_ref,
    })
}

fn derive_address(
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<TonAddress, WalletLifecycleError> {
    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

    let wallet = derive_wallet(phrase, network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(wallet.address.clone())
}

fn recovery_phrase(secret: &SensitiveMnemonic) -> Result<RecoveryPhrase, WalletLifecycleError> {
    Ok(RecoveryPhrase {
        phrase: secret
            .as_str()
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?
            .to_owned(),
    })
}

fn sign_ton_connect_proof(
    secret: &SensitiveMnemonic,
    request: &TonConnectProofSignRequest,
) -> Result<TonConnectProofSignature, WalletLifecycleError> {
    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
    let wallet = derive_wallet(phrase, request.descriptor.network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;
    if wallet.address != *request.descriptor.address.as_address()
        || wallet.key_pair.public_key.as_slice() != request.descriptor.public_key
    {
        return Err(WalletLifecycleError::SecretWalletMismatch);
    }

    let address_hash = <[u8; 32]>::try_from(wallet.address.hash.as_slice())
        .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)?;
    let address = RawAccountAddress::new(wallet.address.workchain, address_hash);
    let digest = ton_proof_signing_hash(
        &address,
        &request.domain,
        request.timestamp,
        &request.payload,
    )
    .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)?;
    let signing_key = SigningKey::from_keypair_bytes(&wallet.key_pair.secret_key)
        .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)?;
    if signing_key.verifying_key().to_bytes() != wallet.key_pair.public_key {
        return Err(WalletLifecycleError::SecretWalletMismatch);
    }

    Ok(TonConnectProofSignature {
        signature: signing_key.sign(&digest).to_bytes().to_vec(),
    })
}

fn derive_ton_connect_account(
    descriptor: WalletDescriptor,
) -> Result<TonConnectAccountInfo, WalletLifecycleError> {
    validate_descriptor(&descriptor)?;
    let (address, state_init) =
        derive_wallet_public_state(&descriptor.public_key, descriptor.network)
            .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;
    let wallet_state_init = state_init
        .to_boc_base64()
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(TonConnectAccountInfo {
        address: address.to_hex(),
        network: match descriptor.network {
            Network::Mainnet => "-239",
            Network::Testnet => "-3",
        }
        .to_owned(),
        wallet_state_init,
        public_key: descriptor.public_key,
    })
}

fn secret_ref_for(record_id: &str) -> ProtectedSecretRef {
    ProtectedSecretRef {
        value: format!("wallet:{record_id}:mnemonic"),
    }
}

fn validate_descriptor(descriptor: &WalletDescriptor) -> Result<(), WalletLifecycleError> {
    validate_record_id(&descriptor.record_id)?;

    let (derived_address, _) =
        derive_wallet_public_state(&descriptor.public_key, descriptor.network)
            .map_err(|_| WalletLifecycleError::InvalidRecordId)?;

    if descriptor.secret_ref != secret_ref_for(&descriptor.record_id)
        || descriptor.address.as_address() != &derived_address
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

fn validate_record_id(record_id: &str) -> Result<(), WalletLifecycleError> {
    if record_id.is_empty()
        || record_id.len() > MAX_RECORD_ID_BYTES
        || !record_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::str::FromStr as _;

    use super::*;

    const MNEMONIC: &str = "notice tortoise soup strong gun divide offer process salon siren general carry clump left year void clutch tool case burden fix income champion lounge";

    #[test]
    fn descriptor_rejects_each_broken_identity_binding_independently() {
        let descriptor = valid_descriptor();
        assert_eq!(validate_descriptor(&descriptor), Ok(()));

        let mut wrong_secret = descriptor.clone();
        wrong_secret.secret_ref = ProtectedSecretRef {
            value: "wallet:another-record:mnemonic".to_owned(),
        };
        assert_eq!(
            validate_descriptor(&wrong_secret),
            Err(WalletLifecycleError::InvalidRecordId)
        );

        let mut wrong_address = descriptor;
        wrong_address.address = TonAddressString::try_from(
            "0:1111111111111111111111111111111111111111111111111111111111111111",
        )
        .expect("valid alternate TON address");
        assert_eq!(
            validate_descriptor(&wrong_address),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }

    #[test]
    fn record_identifier_enforces_each_boundary_independently() {
        assert_eq!(
            validate_record_id(""),
            Err(WalletLifecycleError::InvalidRecordId)
        );
        assert_eq!(
            validate_record_id("invalid/value"),
            Err(WalletLifecycleError::InvalidRecordId)
        );
        assert_eq!(validate_record_id(&"a".repeat(MAX_RECORD_ID_BYTES)), Ok(()));
        assert_eq!(
            validate_record_id(&"a".repeat(MAX_RECORD_ID_BYTES + 1)),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }

    #[test]
    fn ton_connect_proof_signing_is_bound_to_the_descriptor_and_fields()
    -> Result<(), Box<dyn std::error::Error>> {
        let words = MNEMONIC
            .split_whitespace()
            .map(str::to_owned)
            .collect::<Vec<_>>();
        let secret = SensitiveMnemonic::from_words(words)?;
        let descriptor = derive_descriptor("ton-connect-proof", Network::Testnet, &secret)?;
        let request = TonConnectProofSignRequest {
            descriptor: descriptor.clone(),
            domain: "wallet.example".to_owned(),
            timestamp: 1_800_000_000,
            payload: "one-time challenge".to_owned(),
        };
        let signed = sign_ton_connect_proof(&secret, &request)?;
        let signature = <[u8; 64]>::try_from(signed.signature.as_slice())?;
        let public_key = <[u8; 32]>::try_from(descriptor.public_key.as_slice())?;
        let address = descriptor.address.as_address();
        let address_hash = <[u8; 32]>::try_from(address.hash.as_slice())?;
        let raw_address = RawAccountAddress::new(address.workchain, address_hash);
        let hash = ton_proof_signing_hash(
            &raw_address,
            &request.domain,
            request.timestamp,
            &request.payload,
        )?;

        assert!(ton_connect_core::verify_signature(
            &hash,
            &ton_connect_core::Ed25519Signature::from_bytes(signature),
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
            ton_connect_core::SignatureDomain::Empty,
        )?);

        let changed_hash = ton_proof_signing_hash(
            &raw_address,
            &request.domain,
            request.timestamp,
            "different challenge",
        )?;
        assert!(!ton_connect_core::verify_signature(
            &changed_hash,
            &ton_connect_core::Ed25519Signature::from_bytes(signature),
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
            ton_connect_core::SignatureDomain::Empty,
        )?);
        Ok(())
    }

    #[test]
    fn ton_connect_account_material_is_self_consistent() -> Result<(), Box<dyn std::error::Error>> {
        let info = derive_ton_connect_account(valid_descriptor())?;
        let state_init = ton_connect_core::WalletStateInit::try_from(info.wallet_state_init)?;
        let address = RawAccountAddress::from_str(&info.address)?;
        let public_key = <[u8; 32]>::try_from(info.public_key.as_slice())?;
        let verified = state_init.verify_standard_wallet(
            &address,
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
        )?;

        assert_eq!(info.network, "-3");
        assert_eq!(
            verified.version(),
            ton_connect_core::StandardWalletVersion::Wallet
        );
        Ok(())
    }

    /// Rejects persisted wallet metadata that cannot reconstruct its account state.
    #[test]
    fn descriptor_without_public_key_is_rejected() -> Result<(), Box<dyn std::error::Error>> {
        let descriptor = valid_descriptor();
        let mut json = serde_json::to_value(descriptor)?;
        let object = json
            .as_object_mut()
            .ok_or("wallet descriptor must serialize as an object")?;
        let _ = object.remove("publicKey");

        assert!(serde_json::from_value::<WalletDescriptor>(json).is_err());
        Ok(())
    }

    fn valid_descriptor() -> WalletDescriptor {
        let record_id = "wallet-record";
        let public_key = vec![0; 32];
        let (address, _) = derive_wallet_public_state(&public_key, Network::Testnet)
            .expect("32-byte public key derives a wallet");

        WalletDescriptor {
            record_id: record_id.to_owned(),
            address: TonAddressString::from_address(&address, Network::Testnet),
            public_key,
            network: Network::Testnet,
            secret_ref: secret_ref_for(record_id),
        }
    }
}
