//! Wallet lifecycle, key derivation, and transfer construction.
//!
//! The public API creates and imports wallets while the host stores recovery
//! words. Private submodules derive wallet keys and build signed transfers.

pub(crate) mod crypto;
pub(crate) mod encrypted_comment;
pub(crate) mod key_history;
pub(crate) mod key_rotation;
pub(crate) mod mnemonic;
mod mnemonic_scheme;
pub(crate) mod nft_transfer;
pub(crate) mod recipient_public_key;
pub(crate) mod send;
pub(crate) mod slip_0010;
pub(crate) mod transfer;

pub use mnemonic_scheme::{MnemonicScheme, detect_mnemonic_schemes, rotation_mnemonic_public_key};

use std::sync::Arc;

use ton::ton_core::{traits::tlb::TLB as _, types::TonAddress};
use ton_connect_core::{
    ClientId, NetworkId, RawAccountAddress, ValueError, ton_proof_signing_hash,
};

use self::crypto::{
    SensitiveMnemonic, SensitiveWallet, derive_wallet, derive_wallet_public_state,
    generate_mnemonic,
};
use crate::domain::{
    Network, ProtectedSecretHostError, ProtectedSecretHostErrorKind, ProtectedSecretRead,
    ProtectedSecretRef, ProtectedSecretStore, SecretAccessReason, bounded_diagnostic,
};
use crate::engine::WalletPlatformHost;
use crate::types::TonAddressExt as _;
use crate::{
    Boc, TonAddressString, TonConnectDerivedSession, TonConnectDerivedSessionRequest,
    TonConnectSignDataSignRequest, TonConnectSignedData,
};

const MAX_RECORD_ID_BYTES: usize = 128;

/// Public, persistable wallet metadata. Recovery words never belong here.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletDescriptor {
    /// The stable application record identifier.
    pub record_id: String,
    /// The derived friendly non-bounceable TON address.
    pub address: TonAddressString,
    /// The raw 32-byte Ed25519 anchor public key of the rotation mnemonic.
    ///
    /// The anchor key determines the wallet account address and never
    /// changes, so this is safe to persist. It lets the engine emulate a
    /// first deployment before it asks the host to unlock the recovery
    /// phrase.
    pub public_key: Vec<u8>,
    /// The network used for derivation and future operations.
    pub network: Network,
    /// The host protected-storage reference for the mnemonic.
    pub secret_ref: ProtectedSecretRef,
}

/// Requests an address-bound off-chain TON Connect ownership proof signature.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectProofSignRequest {
    /// Wallet whose protected key must sign the proof.
    pub descriptor: WalletDescriptor,
    /// Exact manifest domain shown to and approved by the user.
    pub domain: String,
    /// Unix signing timestamp in seconds.
    pub timestamp: u64,
    /// Exact dApp challenge from the `ton_proof` connect item.
    pub payload: String,
}

/// Ed25519 result of an authorized TON Connect ownership proof.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectProofSignature {
    /// Exact 64-byte Ed25519 signature.
    pub signature: Vec<u8>,
    /// Current 32-byte Ed25519 signing public key used for this proof.
    ///
    /// Use this key in the accompanying `ton_addr` reply. After rotation it
    /// differs from the anchor key in the descriptor and initial `StateInit`.
    pub public_key: Vec<u8>,
}

/// Public account material sent in a TON Connect `ton_addr` reply.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct TonConnectAccountInfo {
    /// Canonical raw TON address (`workchain:hex`).
    pub address: String,
    /// TON network global ID encoded as a decimal string.
    pub network: String,
    /// Canonical standard-base64 wallet `StateInit` `BoC`.
    pub wallet_state_init: String,
    /// Raw 32-byte Ed25519 public key advertised to the dApp.
    ///
    /// [`WalletLifecycle::ton_connect_account`] supplies the initial anchor
    /// key. When signing a proof, replace it with the returned signing key.
    pub public_key: Vec<u8>,
}

/// Requests generation of a new wallet account.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreateWalletRequest {
    /// Stable application identity, normally a UUID generated by the host.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
}

/// A secret-bearing one-shot command. It must never be persisted or logged.
///
/// The words cross FFI because the user enters them. Rust validates and derives
/// the wallet. The host only provides protected storage.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ImportWalletRequest {
    /// The stable application record identifier for the imported wallet.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
    /// Lowercase English words of a rotation mnemonic (TEP-0003 section 3.3).
    ///
    /// Pass the phrase exactly as the user recorded it: 12 words for a wallet
    /// whose key was never rotated, or 24 words - two independently
    /// checksummed BIP-39 halves - after rotation. The engine expands the
    /// 12-word form itself; never duplicate the words in the application.
    ///
    /// [`detect_mnemonic_schemes`] classifies the same word vector without
    /// importing it, so the application can explain a rejection.
    pub recovery_words: Vec<String>,
}

/// A deliberately one-shot presentation value, not wallet state.
///
/// The UI must discard this value as soon as the recovery-phrase screen is
/// dismissed. Neither `WalletDescriptor` nor `WalletSnapshot` contains it.
///
/// A newly created wallet has a 12-word phrase; the phrase becomes 24 words
/// when the wallet's key is rotated.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryPhrase {
    /// The recovery words in order, separated by one ASCII space.
    ///
    /// Keeping the phrase in one allocation avoids separately allocated
    /// secret strings at the FFI boundary. Split it only while presenting
    /// individual words, then release those temporary views.
    pub phrase: String,
}

/// Result of creating a wallet.
///
/// The descriptor is safe to persist. The recovery phrase is transient and
/// exists only so the UI can show it once.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreatedWallet {
    /// Metadata that the application must persist.
    pub descriptor: WalletDescriptor,
    /// A transient phrase that the application can present once.
    pub recovery_phrase: RecoveryPhrase,
}

/// Selects how the signed key-rotation request will reach Wallet rev00.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum KeyRotationMessageKind {
    /// Complete incoming external message for direct provider submission.
    External,
    /// Complete owner-signed internal message for a gas-paying relayer.
    Internal,
}

/// Requests creation of the data needed for Wallet rev00 key rotation.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct PrepareKeyRotationRequest {
    /// Unix timestamp covered by the current key's request signature.
    pub valid_until: u64,
    /// Delivery channel and channel-specific request opcode.
    pub message_kind: KeyRotationMessageKind,
}

/// One-shot data prepared for a Wallet rev00 signing-key rotation.
///
/// This value does not mean that rotation succeeded on-chain. Before
/// submission, the host must store `replacement_recovery_phrase` in protected
/// storage. It must store `signed_boc` as a pending durable record. Words 13-24
/// are the new signing half. Until chain state resolves the request, the host
/// must block ordinary signing.
///
/// The signed request also carries `encryptedOldPrivateKey`, computed over
/// 32-byte Ed25519 seeds as
/// `sha256(new_private_key ‖ "keyChangeSaltV1") XOR old_private_key`, where the
/// old key is the signing key being replaced. Only the new key opens it. The
/// contract publishes it in its key-changed log, so
/// [`crate::WalletClient::decrypt_comment`] can later recover the replaced key.
/// The engine adds it to `signed_boc`; the host handles nothing extra.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct PreparedKeyRotation {
    /// Full 24-word phrase that preserves the anchor and contains the new signing half.
    pub replacement_recovery_phrase: RecoveryPhrase,
    /// New raw 32-byte Ed25519 signing public key stored by the contract on success.
    pub new_public_key: Vec<u8>,
    /// Complete external or relaxed internal signed message as a validated BOC.
    ///
    /// Its `ChangePublicKey` request holds two references: the new key's
    /// wallet-address proof signature and the encrypted old private key.
    pub signed_boc: Boc,
    /// Sequence number covered by the signed request.
    pub seqno: u32,
    /// Unix expiration timestamp covered by the signed request.
    pub valid_until: u64,
    /// Delivery channel encoded into the request opcode.
    pub message_kind: KeyRotationMessageKind,
}

/// A wallet creation, import, secret, or derivation failure.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[uniffi::export(Display)]
#[serde(rename_all = "camelCase")]
pub enum WalletLifecycleError {
    /// The record ID is empty, too long, or contains unsupported characters.
    #[error("invalid wallet record identifier")]
    InvalidRecordId,
    /// The recovery phrase is not a valid 12- or 24-word Rotation mnemonic.
    ///
    /// [`detect_mnemonic_schemes`] reports whether the words form a TON or
    /// 24-word BIP-39 mnemonic instead, so the application can say why the
    /// phrase was rejected.
    #[error("invalid recovery phrase")]
    InvalidRecoveryPhrase,
    /// Rust cannot construct the requested wallet address.
    #[error("wallet address derivation failed")]
    AddressDerivationFailed,
    /// The TON Connect proof fields or signing key are invalid.
    #[error("TON Connect ownership proof signing failed")]
    TonConnectSigningFailed,
    /// The protected mnemonic derives a different address from the descriptor.
    #[error("protected recovery phrase does not belong to this wallet")]
    SecretWalletMismatch,
    /// The host reported a protected-storage failure.
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    ProtectedSecretHost {
        /// The stable host failure classification.
        kind: ProtectedSecretHostErrorKind,
        /// A sanitized developer-facing diagnostic.
        diagnostic: String,
    },
    /// The dApp client id is not 64 lowercase hex characters or the session nonce is empty.
    #[error("invalid TON Connect session input")]
    InvalidTonConnectSessionInput,
}

impl From<ProtectedSecretHostError> for WalletLifecycleError {
    fn from(value: ProtectedSecretHostError) -> Self {
        match value {
            ProtectedSecretHostError::Failed { kind, diagnostic } => Self::ProtectedSecretHost {
                kind,
                diagnostic: bounded_diagnostic(diagnostic),
            },
        }
    }
}

/// Coordinates wallet creation and recovery-phrase access.
///
/// It intentionally has no stream, refresh, reconciliation, or journal API.
/// The embedding application owns public wallet metadata. This object owns the
/// boundary between Rust key derivation and protected storage.
#[derive(uniffi::Object)]
pub struct WalletLifecycle {
    platform_host: Arc<dyn WalletPlatformHost>,
}

#[uniffi::export]
impl WalletLifecycle {
    #[uniffi::constructor]
    /// Creates a lifecycle service backed by `platform_host`.
    ///
    /// The application can share this object across wallet operations. The
    /// application remains responsible for the lifetime of host resources.
    pub fn new(platform_host: Arc<dyn WalletPlatformHost>) -> Arc<Self> {
        Arc::new(Self { platform_host })
    }

    /// Generates the initial 12-word recovery phrase, derives its wallet
    /// account, and stores the phrase.
    ///
    /// A new wallet starts before its first key rotation, so its signing
    /// key equals its anchor key and the user records a single 12-word half.
    ///
    /// Persist `descriptor` after this method succeeds. Present the recovery
    /// phrase once, then release all application copies of it.
    pub async fn create_wallet(
        &self,
        request: CreateWalletRequest,
    ) -> Result<CreatedWallet, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret =
            generate_mnemonic().map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        let recovery_phrase = recovery_phrase(&secret)?;

        Ok(CreatedWallet {
            descriptor,
            recovery_phrase,
        })
    }

    /// Validates and imports an entered mnemonic as a wallet account.
    ///
    /// The host stores the phrase with a user-presence requirement. The result
    /// contains only metadata that is safe for normal application storage.
    pub async fn import_wallet(
        &self,
        request: ImportWalletRequest,
    ) -> Result<WalletDescriptor, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret = SensitiveMnemonic::from_words(request.recovery_words)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        Ok(descriptor)
    }

    /// Authorizes secret access and returns a verified recovery phrase.
    ///
    /// Rust derives an address from the returned secret and compares it with
    /// the descriptor. Release the returned phrase after the UI closes.
    pub async fn reveal_recovery_phrase(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<RecoveryPhrase, WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: descriptor.secret_ref.clone(),
                reason: SecretAccessReason::RevealRecoveryPhrase,
                prompt: "Authenticate to reveal this wallet's recovery phrase".to_owned(),
            })
            .await?;

        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let actual = derive_address(descriptor.network, &secret)?;
        let expected = descriptor.address.as_address();

        if &actual != expected {
            return Err(WalletLifecycleError::SecretWalletMismatch);
        }

        recovery_phrase(&secret)
    }

    /// Deletes the protected secret for a wallet descriptor.
    ///
    /// This method does not delete application metadata or journal records.
    /// Delete the stored descriptor only after this method succeeds.
    pub async fn delete_wallet(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<(), WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        self.platform_host
            .delete_protected_secret(descriptor.secret_ref)
            .await
            .map_err(Into::into)
    }

    /// Authorizes the current signing key and signs a TON Connect ownership proof.
    ///
    /// Rust constructs the protocol digest itself. The caller cannot use this
    /// API as a generic Ed25519 signing oracle, and no mnemonic or private-key
    /// bytes cross the API boundary.
    /// The returned public key must accompany the proof in `ton_addr`.
    /// The host must block this operation while a key rotation is unresolved.
    pub async fn sign_ton_connect_proof(
        &self,
        request: TonConnectProofSignRequest,
    ) -> Result<TonConnectProofSignature, WalletLifecycleError> {
        validate_descriptor(&request.descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: request.descriptor.secret_ref.clone(),
                reason: SecretAccessReason::SignTonConnectProof,
                prompt: format!(
                    "Authenticate to sign in to {} with TON Connect",
                    request.domain
                ),
            })
            .await?;
        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

        sign_ton_connect_proof(&secret, &request)
    }

    /// Authorizes the current signing key and derives one `MTProto` TON Connect session.
    ///
    /// Scheme v1: the session secret is HMAC-derived from the signing-key seed, the
    /// dApp client id and the server nonce, so every device of the user derives the
    /// same key pair. The returned object exposes only the public key `W` and the
    /// signing public key it was derived from; the engine does not persist it.
    /// A signing-key rotation changes the derived key of every later derivation.
    pub async fn derive_ton_connect_session(
        &self,
        request: TonConnectDerivedSessionRequest,
    ) -> Result<Arc<TonConnectDerivedSession>, WalletLifecycleError> {
        validate_descriptor(&request.descriptor)?;
        let peer = request
            .dapp_client_id
            .parse::<ClientId>()
            .map_err(|_| WalletLifecycleError::InvalidTonConnectSessionInput)?;
        if request.nonce.is_empty() {
            return Err(WalletLifecycleError::InvalidTonConnectSessionInput);
        }

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: request.descriptor.secret_ref.clone(),
                reason: SecretAccessReason::DeriveTonConnectSessionKey,
                prompt: "Authenticate to connect this wallet with TON Connect".to_owned(),
            })
            .await?;
        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

        derive_ton_connect_session(&secret, &request, peer)
    }

    /// Authorizes the current signing key and signs one TON Connect `signData` request.
    ///
    /// Rust validates the request against this wallet and builds the protocol digest
    /// for `domain` and `timestamp` before any secret access, so the caller cannot use
    /// this API as a generic signing oracle. The returned record is what
    /// `TonConnectDerivedSession::encrypt_sign_data_success` answers with. The host
    /// must block this operation while a key rotation is unresolved.
    pub async fn sign_ton_connect_data(
        &self,
        request: TonConnectSignDataSignRequest,
    ) -> Result<TonConnectSignedData, WalletLifecycleError> {
        validate_descriptor(&request.descriptor)?;
        let digest = sign_data_digest(&request)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: request.descriptor.secret_ref.clone(),
                reason: SecretAccessReason::SignTonConnectData,
                prompt: format!(
                    "Authenticate to sign data for {} with TON Connect",
                    request.domain
                ),
            })
            .await?;
        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

        sign_ton_connect_data(&secret, request, &digest)
    }

    /// Derives initial TON Connect account material without reading a secret.
    ///
    /// Address and `StateInit` remain anchor-based after rotation. For a proof
    /// reply, replace `public_key` with [`TonConnectProofSignature::public_key`].
    pub fn ton_connect_account(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<TonConnectAccountInfo, WalletLifecycleError> {
        derive_ton_connect_account(descriptor)
    }
}

impl WalletLifecycle {
    async fn store(
        &self,
        secret_ref: &ProtectedSecretRef,
        bytes: &[u8],
    ) -> Result<(), WalletLifecycleError> {
        self.platform_host
            .store_protected_secret(ProtectedSecretStore {
                secret_ref: secret_ref.clone(),
                bytes: bytes.to_vec(),
                // This is an access-control requirement for subsequent reads,
                // not a request to prompt while creating the item.
                require_user_presence: true,
            })
            .await
            .map_err(Into::into)
    }
}

fn derive_descriptor(
    record_id: &str,
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<WalletDescriptor, WalletLifecycleError> {
    let secret_ref = secret_ref_for(record_id);

    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
    let wallet = derive_wallet(phrase, network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(WalletDescriptor {
        record_id: record_id.to_owned(),
        address: TonAddressString::try_from(wallet.address.to_user_friendly(network))
            .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?,
        public_key: wallet.key_pair.public_key.to_vec(),
        network,
        secret_ref,
    })
}

fn derive_address(
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<TonAddress, WalletLifecycleError> {
    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

    let wallet = derive_wallet(phrase, network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(wallet.address.clone())
}

fn recovery_phrase(secret: &SensitiveMnemonic) -> Result<RecoveryPhrase, WalletLifecycleError> {
    Ok(RecoveryPhrase {
        phrase: secret
            .as_str()
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?
            .to_owned(),
    })
}

fn sign_ton_connect_proof(
    secret: &SensitiveMnemonic,
    request: &TonConnectProofSignRequest,
) -> Result<TonConnectProofSignature, WalletLifecycleError> {
    let wallet = unlock_wallet(secret, &request.descriptor)?;
    let digest = ton_proof_signing_hash(
        &ton_connect_address(&request.descriptor),
        &request.domain,
        request.timestamp,
        &request.payload,
    )
    .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)?;
    Ok(TonConnectProofSignature {
        signature: wallet.sign_ton_connect_digest(&digest).to_vec(),
        public_key: wallet.signing_public_key().to_vec(),
    })
}

fn derive_ton_connect_session(
    secret: &SensitiveMnemonic,
    request: &TonConnectDerivedSessionRequest,
    peer: ClientId,
) -> Result<Arc<TonConnectDerivedSession>, WalletLifecycleError> {
    let wallet = unlock_wallet(secret, &request.descriptor)?;
    let network = ton_connect_network(request.descriptor.network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;
    Ok(TonConnectDerivedSession::new(
        wallet.ton_connect_session_secret(&peer.to_bytes(), &request.nonce),
        peer,
        wallet.signing_public_key(),
        ton_connect_address(&request.descriptor),
        network,
    ))
}

/// Validates a `signData` request against the descriptor's wallet and returns its digest.
///
/// `validate_descriptor` has already proved the descriptor address is the one its
/// anchor key derives, so no secret is needed.
fn sign_data_digest(
    request: &TonConnectSignDataSignRequest,
) -> Result<[u8; 32], WalletLifecycleError> {
    crate::ton_connect::sign_data_digest(
        &request.request,
        &ton_connect_network(request.descriptor.network)
            .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)?,
        &ton_connect_address(&request.descriptor),
        &request.domain,
        request.timestamp,
    )
    .map_err(|_| WalletLifecycleError::TonConnectSigningFailed)
}

fn sign_ton_connect_data(
    secret: &SensitiveMnemonic,
    request: TonConnectSignDataSignRequest,
    digest: &[u8; 32],
) -> Result<TonConnectSignedData, WalletLifecycleError> {
    let wallet = unlock_wallet(secret, &request.descriptor)?;
    Ok(TonConnectSignedData {
        request: request.request,
        domain: request.domain,
        timestamp: request.timestamp,
        signature: wallet.sign_ton_connect_digest(digest).to_vec(),
        public_key: wallet.signing_public_key().to_vec(),
    })
}

/// Derives the wallet from its protected secret and checks it is the descriptor's wallet.
fn unlock_wallet(
    secret: &SensitiveMnemonic,
    descriptor: &WalletDescriptor,
) -> Result<SensitiveWallet, WalletLifecycleError> {
    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
    let wallet = derive_wallet(phrase, descriptor.network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;
    if wallet.address != *descriptor.address.as_address()
        || wallet.key_pair.public_key.as_slice() != descriptor.public_key
    {
        return Err(WalletLifecycleError::SecretWalletMismatch);
    }
    Ok(wallet)
}

/// The descriptor's (anchor-derived) wallet address in TON Connect's raw form.
fn ton_connect_address(descriptor: &WalletDescriptor) -> RawAccountAddress {
    let address = descriptor.address.as_address();
    RawAccountAddress::new(address.workchain, *address.hash.as_slice_sized())
}

/// The TON Connect network ID (`network_global_id`) of a network.
fn ton_connect_network(network: Network) -> Result<NetworkId, ValueError> {
    NetworkId::try_from(network.global_id())
}

fn derive_ton_connect_account(
    descriptor: WalletDescriptor,
) -> Result<TonConnectAccountInfo, WalletLifecycleError> {
    validate_descriptor(&descriptor)?;
    let (address, state_init) =
        derive_wallet_public_state(&descriptor.public_key, descriptor.network)
            .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;
    let wallet_state_init = state_init
        .to_boc_base64()
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(TonConnectAccountInfo {
        address: address.to_hex(),
        network: descriptor.network.global_id().to_owned(),
        wallet_state_init,
        public_key: descriptor.public_key,
    })
}

fn secret_ref_for(record_id: &str) -> ProtectedSecretRef {
    ProtectedSecretRef {
        value: format!("wallet:{record_id}:mnemonic"),
    }
}

fn validate_descriptor(descriptor: &WalletDescriptor) -> Result<(), WalletLifecycleError> {
    validate_record_id(&descriptor.record_id)?;

    let (derived_address, _) =
        derive_wallet_public_state(&descriptor.public_key, descriptor.network)
            .map_err(|_| WalletLifecycleError::InvalidRecordId)?;

    if descriptor.secret_ref != secret_ref_for(&descriptor.record_id)
        || descriptor.address.as_address() != &derived_address
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

fn validate_record_id(record_id: &str) -> Result<(), WalletLifecycleError> {
    if record_id.is_empty()
        || record_id.len() > MAX_RECORD_ID_BYTES
        || !record_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::str::FromStr as _;
    use std::sync::Mutex;

    use futures::executor::block_on;
    use serde_json::json;
    use ton_connect_core::{
        AppRequest, KnownWalletResponse, SessionCrypto, SignDataResult, WalletResponse,
    };

    use super::*;
    use crate::{
        JournalCompareExchange, JournalCompareExchangeResult, JournalHostError, JournalKey,
        JournalRecord, TonConnectIncomingRequest, TonConnectSignDataPayload,
        TonConnectSignDataRequest,
    };

    const MNEMONIC: &str = "notice tortoise soup strong gun divide offer process salon siren general carry clump left year void clutch tool case burden fix income champion lounge";

    /// The dApp client id of the fixed vector (the tweetnacl "alice" public key).
    const DAPP_CLIENT_ID: &str = "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a";

    /// Serves one fixed phrase and records every access reason; with no phrase,
    /// any secret read fails the test.
    struct PhraseHost {
        phrase: Option<&'static str>,
        reasons: Mutex<Vec<SecretAccessReason>>,
    }

    #[async_trait::async_trait]
    impl WalletPlatformHost for PhraseHost {
        async fn read_protected_secret(
            &self,
            request: ProtectedSecretRead,
        ) -> Result<Vec<u8>, ProtectedSecretHostError> {
            let phrase = self
                .phrase
                .expect("invalid input must be refused before the secret is read");
            self.reasons
                .lock()
                .expect("reason lock")
                .push(request.reason);
            Ok(phrase.as_bytes().to_vec())
        }

        async fn store_protected_secret(
            &self,
            _request: ProtectedSecretStore,
        ) -> Result<(), ProtectedSecretHostError> {
            panic!("not used by TON Connect signing")
        }

        async fn delete_protected_secret(
            &self,
            _secret_ref: ProtectedSecretRef,
        ) -> Result<(), ProtectedSecretHostError> {
            panic!("not used by TON Connect signing")
        }

        async fn load_journal(
            &self,
            _key: JournalKey,
        ) -> Result<Option<JournalRecord>, JournalHostError> {
            panic!("not used by TON Connect signing")
        }

        async fn compare_exchange_journal(
            &self,
            _mutation: JournalCompareExchange,
        ) -> Result<JournalCompareExchangeResult, JournalHostError> {
            panic!("not used by TON Connect signing")
        }
    }

    fn phrase_host(phrase: &'static str) -> Arc<PhraseHost> {
        Arc::new(PhraseHost {
            phrase: Some(phrase),
            reasons: Mutex::new(Vec::new()),
        })
    }

    fn no_secrets_host() -> Arc<PhraseHost> {
        Arc::new(PhraseHost {
            phrase: None,
            reasons: Mutex::new(Vec::new()),
        })
    }

    /// The first 12 words of [`MNEMONIC`]: the same wallet before its key rotation.
    const INITIAL_MNEMONIC: &str =
        "notice tortoise soup strong gun divide offer process salon siren general carry";

    fn expected_w(seed: &[u8; 32], a: &[u8; 32], nonce: &[u8]) -> String {
        SessionCrypto::from_secret_key(*crypto::derive_ton_connect_session_secret(seed, a, nonce))
            .client_id()
            .to_string()
    }

    #[test]
    fn derived_session_uses_the_signing_key_and_records_its_reason()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_bytes(MNEMONIC.as_bytes().to_vec())?;
        let descriptor = derive_descriptor("ton-connect-derived", Network::Testnet, &secret)?;
        let a = DAPP_CLIENT_ID.parse::<ClientId>()?.to_bytes();
        let nonce = vec![1_u8, 2, 3];
        let host = phrase_host(MNEMONIC);
        let session = block_on(
            WalletLifecycle::new(host.clone()).derive_ton_connect_session(
                TonConnectDerivedSessionRequest {
                    descriptor: descriptor.clone(),
                    dapp_client_id: DAPP_CLIENT_ID.to_owned(),
                    nonce: nonce.clone(),
                },
            ),
        )?;
        assert_eq!(
            *host.reasons.lock().expect("reason lock"),
            vec![SecretAccessReason::DeriveTonConnectSessionKey]
        );

        let mnemonic = mnemonic::RotationMnemonic::parse(MNEMONIC)?;
        let keys = crypto::derive_rotation_keys(&mnemonic);
        let expected_signing_key = crypto::derive_half_key(mnemonic.signing());
        assert_eq!(
            session.signing_public_key(),
            expected_signing_key.verifying_key().to_bytes().to_vec()
        );
        assert_ne!(
            session.signing_public_key(),
            descriptor.public_key,
            "fixture must contain a rotated key"
        );

        let from_signing = expected_w(keys.signing.as_bytes(), &a, &nonce);
        let from_anchor = expected_w(keys.anchor.as_bytes(), &a, &nonce);
        assert_eq!(session.public_key_hex(), from_signing);
        assert_ne!(session.public_key_hex(), from_anchor);
        Ok(())
    }

    #[test]
    fn derived_session_before_rotation_matches_the_anchor() -> Result<(), Box<dyn std::error::Error>>
    {
        assert_eq!(
            INITIAL_MNEMONIC,
            MNEMONIC
                .split_whitespace()
                .take(12)
                .collect::<Vec<_>>()
                .join(" ")
        );
        let secret = SensitiveMnemonic::from_bytes(INITIAL_MNEMONIC.as_bytes().to_vec())?;
        let descriptor =
            derive_descriptor("ton-connect-derived-initial", Network::Testnet, &secret)?;
        let a = DAPP_CLIENT_ID.parse::<ClientId>()?.to_bytes();
        let nonce = vec![4_u8; 24];
        let session = block_on(
            WalletLifecycle::new(phrase_host(INITIAL_MNEMONIC)).derive_ton_connect_session(
                TonConnectDerivedSessionRequest {
                    descriptor: descriptor.clone(),
                    dapp_client_id: DAPP_CLIENT_ID.to_owned(),
                    nonce: nonce.clone(),
                },
            ),
        )?;

        let keys =
            crypto::derive_rotation_keys(&mnemonic::RotationMnemonic::parse(INITIAL_MNEMONIC)?);
        assert_eq!(keys.anchor.as_bytes(), keys.signing.as_bytes());
        assert_eq!(session.signing_public_key(), descriptor.public_key);
        assert_eq!(
            session.signing_public_key(),
            keys.anchor.verifying_key().to_bytes().to_vec()
        );
        assert_eq!(
            session.public_key_hex(),
            expected_w(keys.anchor.as_bytes(), &a, &nonce)
        );
        Ok(())
    }

    #[test]
    fn invalid_session_input_is_refused_before_the_secret_is_read()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_bytes(MNEMONIC.as_bytes().to_vec())?;
        let descriptor = derive_descriptor("ton-connect-derived-input", Network::Testnet, &secret)?;
        let lifecycle = WalletLifecycle::new(no_secrets_host());
        let requests = [
            TonConnectDerivedSessionRequest {
                descriptor: descriptor.clone(),
                dapp_client_id: DAPP_CLIENT_ID.get(..63).unwrap_or_default().to_owned(),
                nonce: vec![1_u8],
            },
            TonConnectDerivedSessionRequest {
                descriptor: descriptor.clone(),
                dapp_client_id: DAPP_CLIENT_ID.to_ascii_uppercase(),
                nonce: vec![1_u8],
            },
            TonConnectDerivedSessionRequest {
                descriptor,
                dapp_client_id: DAPP_CLIENT_ID.to_owned(),
                nonce: Vec::new(),
            },
        ];
        for request in requests {
            let result = block_on(lifecycle.derive_ton_connect_session(request.clone()));
            assert_eq!(
                result.err(),
                Some(WalletLifecycleError::InvalidTonConnectSessionInput),
                "{request:?}"
            );
        }
        Ok(())
    }

    #[test]
    fn derived_session_binds_the_descriptor() {
        let lifecycle = WalletLifecycle::new(phrase_host(MNEMONIC));
        let result = block_on(lifecycle.derive_ton_connect_session(
            TonConnectDerivedSessionRequest {
                descriptor: valid_descriptor(),
                dapp_client_id: DAPP_CLIENT_ID.to_owned(),
                nonce: vec![1_u8, 2, 3],
            },
        ));
        assert_eq!(
            result.err(),
            Some(WalletLifecycleError::SecretWalletMismatch)
        );
    }

    #[test]
    fn descriptor_rejects_each_broken_identity_binding_independently() {
        let descriptor = valid_descriptor();
        assert_eq!(validate_descriptor(&descriptor), Ok(()));

        let mut wrong_secret = descriptor.clone();
        wrong_secret.secret_ref = ProtectedSecretRef {
            value: "wallet:another-record:mnemonic".to_owned(),
        };
        assert_eq!(
            validate_descriptor(&wrong_secret),
            Err(WalletLifecycleError::InvalidRecordId)
        );

        let mut wrong_address = descriptor;
        wrong_address.address = TonAddressString::try_from(
            "0:1111111111111111111111111111111111111111111111111111111111111111",
        )
        .expect("valid alternate TON address");
        assert_eq!(
            validate_descriptor(&wrong_address),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }

    #[test]
    fn record_identifier_enforces_each_boundary_independently() {
        assert_eq!(
            validate_record_id(""),
            Err(WalletLifecycleError::InvalidRecordId)
        );
        assert_eq!(
            validate_record_id("invalid/value"),
            Err(WalletLifecycleError::InvalidRecordId)
        );
        assert_eq!(validate_record_id(&"a".repeat(MAX_RECORD_ID_BYTES)), Ok(()));
        assert_eq!(
            validate_record_id(&"a".repeat(MAX_RECORD_ID_BYTES + 1)),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }

    #[test]
    fn ton_connect_proof_uses_rotated_signing_key_and_binds_descriptor_and_fields()
    -> Result<(), Box<dyn std::error::Error>> {
        let words = MNEMONIC
            .split_whitespace()
            .map(str::to_owned)
            .collect::<Vec<_>>();
        let secret = SensitiveMnemonic::from_words(words)?;
        let descriptor = derive_descriptor("ton-connect-proof", Network::Testnet, &secret)?;
        let request = TonConnectProofSignRequest {
            descriptor: descriptor.clone(),
            domain: "wallet.example".to_owned(),
            timestamp: 1_800_000_000,
            payload: "one-time challenge".to_owned(),
        };
        let signed = sign_ton_connect_proof(&secret, &request)?;
        let signature = <[u8; 64]>::try_from(signed.signature.as_slice())?;
        let public_key = <[u8; 32]>::try_from(signed.public_key.as_slice())?;
        let anchor_key = <[u8; 32]>::try_from(descriptor.public_key.as_slice())?;
        let mnemonic = mnemonic::RotationMnemonic::parse(MNEMONIC)?;
        let expected_signing_key = crypto::derive_half_key(mnemonic.signing());
        assert_eq!(public_key, expected_signing_key.verifying_key().to_bytes());
        assert_ne!(public_key, anchor_key, "fixture must contain a rotated key");
        let address = descriptor.address.as_address();
        let address_hash = <[u8; 32]>::try_from(address.hash.as_slice())?;
        let raw_address = RawAccountAddress::new(address.workchain, address_hash);
        let hash = ton_proof_signing_hash(
            &raw_address,
            &request.domain,
            request.timestamp,
            &request.payload,
        )?;

        assert!(ton_connect_core::verify_signature(
            &hash,
            &ton_connect_core::Ed25519Signature::from_bytes(signature),
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
            ton_connect_core::SignatureDomain::Empty,
        )?);
        assert!(!ton_connect_core::verify_signature(
            &hash,
            &ton_connect_core::Ed25519Signature::from_bytes(signature),
            &ton_connect_core::Ed25519PublicKey::from_bytes(anchor_key),
            ton_connect_core::SignatureDomain::Empty,
        )?);

        let changed_hash = ton_proof_signing_hash(
            &raw_address,
            &request.domain,
            request.timestamp,
            "different challenge",
        )?;
        assert!(!ton_connect_core::verify_signature(
            &changed_hash,
            &ton_connect_core::Ed25519Signature::from_bytes(signature),
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
            ton_connect_core::SignatureDomain::Empty,
        )?);

        let mut wrong_request = request;
        wrong_request.descriptor = valid_descriptor();
        assert_eq!(
            sign_ton_connect_proof(&secret, &wrong_request),
            Err(WalletLifecycleError::SecretWalletMismatch)
        );
        Ok(())
    }

    #[test]
    fn ton_connect_proof_before_rotation_verifies_with_initial_account()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_words(
            MNEMONIC
                .split_whitespace()
                .take(12)
                .map(str::to_owned)
                .collect(),
        )?;
        let descriptor =
            derive_descriptor("ton-connect-before-rotation", Network::Testnet, &secret)?;
        let account = derive_ton_connect_account(descriptor.clone())?;
        let request = TonConnectProofSignRequest {
            descriptor,
            domain: "wallet.example".to_owned(),
            timestamp: 1_800_000_000,
            payload: "one-time challenge".to_owned(),
        };
        let signed = sign_ton_connect_proof(&secret, &request)?;
        assert_eq!(signed.public_key, account.public_key);
        let account = ton_connect_core::TonAddressItemReply::new(
            RawAccountAddress::from_str(&account.address)?,
            NetworkId::try_from(account.network.as_str())?,
            ton_connect_core::WalletStateInit::try_from(account.wallet_state_init)?,
            ton_connect_core::Ed25519PublicKey::from_bytes(<[u8; 32]>::try_from(
                signed.public_key.as_slice(),
            )?),
        );
        let proof = ton_connect_core::TonProof {
            timestamp: request.timestamp,
            domain: ton_connect_core::TonProofDomain::new(request.domain)?,
            payload: request.payload,
            signature: ton_connect_core::Ed25519Signature::from_bytes(<[u8; 64]>::try_from(
                signed.signature.as_slice(),
            )?),
        };
        assert!(proof.verify_with_account(&account)?);
        Ok(())
    }

    const SIGN_DATA_DOMAIN: &str = "tonconnect-sdk-demo-dapp.vercel.app";
    const SIGN_DATA_TIMESTAMP: u64 = 1_800_000_000;
    const SIGN_DATA_CELL: &str = "te6cckEBAQEADAAAFAAAAABIZWxsbyGVgYQo";
    const SIGN_DATA_SCHEMA: &str =
        "message#_ len:uint7 {len <= 127} text:(bits len * 8) = Message;";

    fn sign_data_payloads() -> [serde_json::Value; 3] {
        [
            json!({"type": "text", "text": "Confirm new 2fa number:\n+1 *** *** ** 89"}),
            json!({"type": "binary", "bytes": "I0hlbGxvLCBXb3JsZCE="}),
            json!({"type": "cell", "schema": SIGN_DATA_SCHEMA, "cell": SIGN_DATA_CELL}),
        ]
    }

    fn text_sign_data_request() -> TonConnectSignDataRequest {
        TonConnectSignDataRequest {
            payload: TonConnectSignDataPayload::Text {
                text: "Approve login".to_owned(),
            },
            network: None,
            from: None,
        }
    }

    /// The dApp side of one `signData` exchange through a real derived session.
    ///
    /// Returns the signed record and the result the dApp validated for its request.
    fn sign_data_round_trip(
        lifecycle: &WalletLifecycle,
        descriptor: &WalletDescriptor,
        id: &str,
        payload: &serde_json::Value,
    ) -> Result<(TonConnectSignedData, SignDataResult), Box<dyn std::error::Error>> {
        let dapp = SessionCrypto::generate()?;
        let session = block_on(lifecycle.derive_ton_connect_session(
            TonConnectDerivedSessionRequest {
                descriptor: descriptor.clone(),
                dapp_client_id: dapp.client_id().to_string(),
                nonce: vec![5_u8; 24],
            },
        ))?;
        let w = session.public_key_hex().parse::<ClientId>()?;
        let app_request = AppRequest {
            method: "signData".to_owned(),
            params: vec![payload.to_string()],
            id: id.to_owned(),
        };
        let body = dapp.encrypt(w, &serde_json::to_vec(&app_request)?)?;
        let decoded = session.decrypt_request(body, SIGN_DATA_TIMESTAMP)?;
        let TonConnectIncomingRequest::SignData {
            id: request_id,
            method,
            request,
        } = decoded.request
        else {
            return Err(format!("request was not decoded as signData: {decoded:?}").into());
        };
        assert_eq!(request_id, id);
        assert_eq!(method, "signData");

        let signed = block_on(
            lifecycle.sign_ton_connect_data(TonConnectSignDataSignRequest {
                descriptor: descriptor.clone(),
                request: request.clone(),
                domain: SIGN_DATA_DOMAIN.to_owned(),
                timestamp: SIGN_DATA_TIMESTAMP,
            }),
        )?;
        assert_eq!(signed.request, request);
        assert_eq!(signed.domain, SIGN_DATA_DOMAIN);
        assert_eq!(signed.timestamp, SIGN_DATA_TIMESTAMP);
        let bytes = session.encrypt_sign_data_success(request_id, signed.clone())?;
        let response = serde_json::from_slice::<WalletResponse>(&dapp.decrypt(w, &bytes)?)?;
        let KnownWalletResponse::SignData(result) =
            response.validate_for(&app_request.decode()?)?
        else {
            return Err("response must be a signData result".into());
        };
        Ok((signed, *result))
    }

    #[test]
    fn sign_data_round_trips_for_each_payload_with_the_rotated_signing_key()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_bytes(MNEMONIC.as_bytes().to_vec())?;
        let descriptor = derive_descriptor("ton-connect-sign-data", Network::Testnet, &secret)?;
        let account = derive_ton_connect_account(descriptor.clone())?;
        let mnemonic = mnemonic::RotationMnemonic::parse(MNEMONIC)?;
        let signing_key = crypto::derive_half_key(mnemonic.signing())
            .verifying_key()
            .to_bytes();
        let anchor_key = <[u8; 32]>::try_from(descriptor.public_key.as_slice())?;
        assert_ne!(
            signing_key, anchor_key,
            "fixture must contain a rotated key"
        );
        let other = ton_connect_core::Ed25519PublicKey::from_bytes(
            ed25519_dalek::SigningKey::from_bytes(&[0x66; 32])
                .verifying_key()
                .to_bytes(),
        );

        let host = phrase_host(MNEMONIC);
        let lifecycle = WalletLifecycle::new(host.clone());
        for (index, payload) in sign_data_payloads().iter().enumerate() {
            let id = format!("{}", index + 1);
            let (signed, result) = sign_data_round_trip(&lifecycle, &descriptor, &id, payload)?;
            assert_eq!(signed.public_key, signing_key.to_vec());
            assert_eq!(signed.signature.len(), 64);
            assert_eq!(serde_json::to_value(&result.payload)?, *payload);
            assert_eq!(result.address.to_string(), account.address);
            assert_eq!(result.domain, SIGN_DATA_DOMAIN);
            assert_eq!(result.timestamp, SIGN_DATA_TIMESTAMP);
            assert!(result.verify(&ton_connect_core::Ed25519PublicKey::from_bytes(signing_key))?);
            assert!(!result.verify(&ton_connect_core::Ed25519PublicKey::from_bytes(anchor_key))?);
            assert!(!result.verify(&other)?);
        }
        assert_eq!(
            *host.reasons.lock().expect("reason lock"),
            [
                SecretAccessReason::DeriveTonConnectSessionKey,
                SecretAccessReason::SignTonConnectData,
                SecretAccessReason::DeriveTonConnectSessionKey,
                SecretAccessReason::SignTonConnectData,
                SecretAccessReason::DeriveTonConnectSessionKey,
                SecretAccessReason::SignTonConnectData,
            ]
        );
        Ok(())
    }

    #[test]
    fn sign_data_before_rotation_verifies_with_the_initial_account()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_bytes(INITIAL_MNEMONIC.as_bytes().to_vec())?;
        let descriptor =
            derive_descriptor("ton-connect-sign-data-initial", Network::Testnet, &secret)?;
        let account = derive_ton_connect_account(descriptor.clone())?;
        let lifecycle = WalletLifecycle::new(phrase_host(INITIAL_MNEMONIC));
        let (signed, result) =
            sign_data_round_trip(&lifecycle, &descriptor, "1", &sign_data_payloads()[0])?;
        assert_eq!(signed.public_key, descriptor.public_key);

        let account = ton_connect_core::TonAddressItemReply::new(
            RawAccountAddress::from_str(&account.address)?,
            NetworkId::try_from(account.network.as_str())?,
            ton_connect_core::WalletStateInit::try_from(account.wallet_state_init)?,
            ton_connect_core::Ed25519PublicKey::from_bytes(<[u8; 32]>::try_from(
                signed.public_key.as_slice(),
            )?),
        );
        assert!(result.verify_with_account(&account)?);
        Ok(())
    }

    #[test]
    fn sign_data_refuses_a_secret_of_another_wallet() {
        let lifecycle = WalletLifecycle::new(phrase_host(MNEMONIC));
        let result = block_on(
            lifecycle.sign_ton_connect_data(TonConnectSignDataSignRequest {
                descriptor: valid_descriptor(),
                request: text_sign_data_request(),
                domain: SIGN_DATA_DOMAIN.to_owned(),
                timestamp: SIGN_DATA_TIMESTAMP,
            }),
        );
        assert_eq!(
            result.err(),
            Some(WalletLifecycleError::SecretWalletMismatch)
        );
    }

    #[test]
    fn invalid_sign_data_input_is_refused_before_the_secret_is_read()
    -> Result<(), Box<dyn std::error::Error>> {
        let secret = SensitiveMnemonic::from_bytes(MNEMONIC.as_bytes().to_vec())?;
        let descriptor =
            derive_descriptor("ton-connect-sign-data-input", Network::Testnet, &secret)?;
        let lifecycle = WalletLifecycle::new(no_secrets_host());
        let sign_request =
            |request: TonConnectSignDataRequest, domain: &str| TonConnectSignDataSignRequest {
                descriptor: descriptor.clone(),
                request,
                domain: domain.to_owned(),
                timestamp: SIGN_DATA_TIMESTAMP,
            };
        let with = |change: fn(&mut TonConnectSignDataRequest)| {
            let mut request = text_sign_data_request();
            change(&mut request);
            request
        };
        let cell = |cell: &str| TonConnectSignDataRequest {
            payload: TonConnectSignDataPayload::Cell {
                schema: SIGN_DATA_SCHEMA.to_owned(),
                cell: cell.to_owned(),
            },
            network: None,
            from: None,
        };
        let refused = [
            sign_request(
                with(|request| request.network = Some("-239".to_owned())),
                SIGN_DATA_DOMAIN,
            ),
            sign_request(
                with(|request| {
                    request.from = Some(
                        "0:1111111111111111111111111111111111111111111111111111111111111111"
                            .to_owned(),
                    );
                }),
                SIGN_DATA_DOMAIN,
            ),
            sign_request(
                with(|request| {
                    request.payload = TonConnectSignDataPayload::Binary {
                        bytes: "not base64!".to_owned(),
                    };
                }),
                SIGN_DATA_DOMAIN,
            ),
            sign_request(cell("not a boc"), SIGN_DATA_DOMAIN),
            sign_request(cell(SIGN_DATA_CELL), "127.0.0.1"),
            sign_request(text_sign_data_request(), "https://app.example/"),
            sign_request(text_sign_data_request(), ""),
        ];
        for request in refused {
            let result = block_on(lifecycle.sign_ton_connect_data(request.clone()));
            assert_eq!(
                result.err(),
                Some(WalletLifecycleError::TonConnectSigningFailed),
                "{request:?}"
            );
        }

        let mut broken = sign_request(text_sign_data_request(), SIGN_DATA_DOMAIN);
        broken.descriptor.record_id = String::new();
        assert_eq!(
            block_on(lifecycle.sign_ton_connect_data(broken)).err(),
            Some(WalletLifecycleError::InvalidRecordId)
        );
        Ok(())
    }

    #[test]
    fn ton_connect_account_material_is_self_consistent() -> Result<(), Box<dyn std::error::Error>> {
        let info = derive_ton_connect_account(valid_descriptor())?;
        let state_init = ton_connect_core::WalletStateInit::try_from(info.wallet_state_init)?;
        let address = RawAccountAddress::from_str(&info.address)?;
        let public_key = <[u8; 32]>::try_from(info.public_key.as_slice())?;
        let verified = state_init.verify_standard_wallet(
            &address,
            &ton_connect_core::Ed25519PublicKey::from_bytes(public_key),
        )?;

        assert_eq!(info.network, "-3");
        assert_eq!(
            verified.version(),
            ton_connect_core::StandardWalletVersion::Wallet
        );
        Ok(())
    }

    /// Rejects persisted wallet metadata that cannot reconstruct its account state.
    #[test]
    fn descriptor_without_public_key_is_rejected() -> Result<(), Box<dyn std::error::Error>> {
        let descriptor = valid_descriptor();
        let mut json = serde_json::to_value(descriptor)?;
        let object = json
            .as_object_mut()
            .ok_or("wallet descriptor must serialize as an object")?;
        let _ = object.remove("publicKey");

        assert!(serde_json::from_value::<WalletDescriptor>(json).is_err());
        Ok(())
    }

    fn valid_descriptor() -> WalletDescriptor {
        let record_id = "wallet-record";
        let public_key = vec![0; 32];
        let (address, _) = derive_wallet_public_state(&public_key, Network::Testnet)
            .expect("32-byte public key derives a wallet");

        WalletDescriptor {
            record_id: record_id.to_owned(),
            address: TonAddressString::from_address(&address, Network::Testnet),
            public_key,
            network: Network::Testnet,
            secret_ref: secret_ref_for(record_id),
        }
    }
}
