//! Wallet lifecycle, key derivation, and V5R1 transfer construction.
//!
//! The public API creates and imports wallets while the host stores recovery
//! words. Private submodules derive wallet keys and build signed transfers.

mod crypto;
pub(crate) mod send;
pub(crate) mod transfer;

use std::str::FromStr;
use std::sync::Arc;
use ton::ton_core::types::TonAddress;

use self::crypto::{SensitiveMnemonic, derive_v5r1_wallet, generate_mnemonic};
use crate::domain::{
    Network, ProtectedSecretHostError, ProtectedSecretHostErrorKind, ProtectedSecretRead,
    ProtectedSecretRef, ProtectedSecretStore, SecretAccessReason, bounded_diagnostic,
};
use crate::engine::WalletPlatformHost;
use crate::types::TonAddressExt as _;

const MAX_RECORD_ID_BYTES: usize = 128;

/// Public, persistable wallet metadata. Recovery words never belong here.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletDescriptor {
    /// The stable application record identifier.
    pub record_id: String,
    /// The derived friendly non-bounceable TON address.
    pub address: String,
    /// The network used for derivation and future operations.
    pub network: Network,
    /// The host protected-storage reference for the mnemonic.
    pub secret_ref: ProtectedSecretRef,
}

/// Requests generation of a new V5R1 wallet.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreateWalletRequest {
    /// Stable application identity, normally a UUID generated by the host.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
}

/// A secret-bearing one-shot command. It must never be persisted or logged.
///
/// The words cross FFI because the user enters them. Rust validates and derives
/// the wallet. The host only provides protected storage.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ImportWalletRequest {
    /// The stable application record identifier for the imported wallet.
    pub record_id: String,
    /// The network used to derive the wallet contract and address.
    pub network: Network,
    /// Exactly 24 lowercase English TON mnemonic words.
    pub recovery_words: Vec<String>,
}

/// A deliberately one-shot presentation value, not wallet state.
///
/// The UI must discard this value as soon as the recovery-phrase screen is
/// dismissed. Neither `WalletDescriptor` nor `WalletSnapshot` contains it.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryPhrase {
    /// The 24 recovery words in order, separated by one ASCII space.
    ///
    /// Keeping the phrase in one allocation avoids 24 separately allocated
    /// secret strings at the FFI boundary. Split it only while presenting
    /// individual words, then release those temporary views.
    pub phrase: String,
}

/// Result of creating a wallet.
///
/// The descriptor is safe to persist. The recovery phrase is transient and
/// exists only so the UI can show it once.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreatedWallet {
    /// Metadata that the application must persist.
    pub descriptor: WalletDescriptor,
    /// A transient phrase that the application can present once.
    pub recovery_phrase: RecoveryPhrase,
}

/// A wallet creation, import, secret, or derivation failure.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum WalletLifecycleError {
    /// The record ID is empty, too long, or contains unsupported characters.
    #[error("invalid wallet record identifier")]
    InvalidRecordId,
    /// The recovery phrase is not a valid 24-word TON mnemonic.
    #[error("invalid recovery phrase")]
    InvalidRecoveryPhrase,
    /// Rust cannot construct the requested V5R1 wallet address.
    #[error("wallet address derivation failed")]
    AddressDerivationFailed,
    /// The protected mnemonic derives a different address from the descriptor.
    #[error("protected recovery phrase does not belong to this wallet")]
    SecretWalletMismatch,
    /// The host reported a protected-storage failure.
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    ProtectedSecretHost {
        /// The stable host failure classification.
        kind: ProtectedSecretHostErrorKind,
        /// A sanitized developer-facing diagnostic.
        diagnostic: String,
    },
}

impl From<ProtectedSecretHostError> for WalletLifecycleError {
    fn from(value: ProtectedSecretHostError) -> Self {
        match value {
            ProtectedSecretHostError::Failed { kind, diagnostic } => Self::ProtectedSecretHost {
                kind,
                diagnostic: bounded_diagnostic(diagnostic),
            },
        }
    }
}

/// Coordinates wallet creation and recovery-phrase access.
///
/// It intentionally has no stream, refresh, reconciliation, or journal API.
/// The embedding application owns public wallet metadata. This object owns the
/// boundary between Rust key derivation and protected storage.
#[derive(uniffi::Object)]
pub struct WalletLifecycle {
    platform_host: Arc<dyn WalletPlatformHost>,
}

#[uniffi::export]
impl WalletLifecycle {
    #[uniffi::constructor]
    /// Creates a lifecycle service backed by `platform_host`.
    ///
    /// The application can share this object across wallet operations. The
    /// application remains responsible for the lifetime of host resources.
    pub fn new(platform_host: Arc<dyn WalletPlatformHost>) -> Arc<Self> {
        Arc::new(Self { platform_host })
    }

    /// Generates and derives a V5R1 wallet, then stores its mnemonic through the host.
    ///
    /// Persist `descriptor` after this method succeeds. Present the recovery
    /// phrase once, then release all application copies of it.
    pub async fn create_wallet(
        &self,
        request: CreateWalletRequest,
    ) -> Result<CreatedWallet, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret =
            generate_mnemonic().map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        let recovery_phrase = recovery_phrase(&secret)?;

        Ok(CreatedWallet {
            descriptor,
            recovery_phrase,
        })
    }

    /// Validates and imports an entered mnemonic as a V5R1 wallet.
    ///
    /// The host stores the phrase with a user-presence requirement. The result
    /// contains only metadata that is safe for normal application storage.
    pub async fn import_wallet(
        &self,
        request: ImportWalletRequest,
    ) -> Result<WalletDescriptor, WalletLifecycleError> {
        validate_record_id(&request.record_id)?;

        let secret = SensitiveMnemonic::from_words(request.recovery_words)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let descriptor = derive_descriptor(&request.record_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        Ok(descriptor)
    }

    /// Authorizes secret access and returns a verified recovery phrase.
    ///
    /// Rust derives an address from the returned secret and compares it with
    /// the descriptor. Release the returned phrase after the UI closes.
    pub async fn reveal_recovery_phrase(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<RecoveryPhrase, WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: descriptor.secret_ref.clone(),
                reason: SecretAccessReason::RevealRecoveryPhrase,
                prompt: "Authenticate to reveal this wallet's recovery phrase".to_owned(),
            })
            .await?;

        let secret = SensitiveMnemonic::from_bytes(bytes)
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let actual = derive_address(descriptor.network, &secret)?;
        let expected = TonAddress::from_str(&descriptor.address)
            .map_err(|_| WalletLifecycleError::InvalidRecordId)?;

        if actual != expected {
            return Err(WalletLifecycleError::SecretWalletMismatch);
        }

        recovery_phrase(&secret)
    }

    /// Deletes the protected secret for a wallet descriptor.
    ///
    /// This method does not delete application metadata or journal records.
    /// Delete the stored descriptor only after this method succeeds.
    pub async fn delete_wallet(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<(), WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        self.platform_host
            .delete_protected_secret(descriptor.secret_ref)
            .await
            .map_err(Into::into)
    }
}

impl WalletLifecycle {
    async fn store(
        &self,
        secret_ref: &ProtectedSecretRef,
        bytes: &[u8],
    ) -> Result<(), WalletLifecycleError> {
        self.platform_host
            .store_protected_secret(ProtectedSecretStore {
                secret_ref: secret_ref.clone(),
                bytes: bytes.to_vec(),
                // This is an access-control requirement for subsequent reads,
                // not a request to prompt while creating the item.
                require_user_presence: true,
            })
            .await
            .map_err(Into::into)
    }
}

fn derive_descriptor(
    record_id: &str,
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<WalletDescriptor, WalletLifecycleError> {
    let secret_ref = secret_ref_for(record_id);

    Ok(WalletDescriptor {
        record_id: record_id.to_owned(),
        address: derive_address(network, secret)?.to_user_friendly(network),
        network,
        secret_ref,
    })
}

fn derive_address(
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<TonAddress, WalletLifecycleError> {
    let phrase = secret
        .as_str()
        .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;

    let wallet = derive_v5r1_wallet(phrase, network)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)?;

    Ok(wallet.address.clone())
}

fn recovery_phrase(secret: &SensitiveMnemonic) -> Result<RecoveryPhrase, WalletLifecycleError> {
    Ok(RecoveryPhrase {
        phrase: secret
            .as_str()
            .map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?
            .to_owned(),
    })
}

fn secret_ref_for(record_id: &str) -> ProtectedSecretRef {
    ProtectedSecretRef {
        value: format!("wallet:{record_id}:mnemonic"),
    }
}

fn validate_descriptor(descriptor: &WalletDescriptor) -> Result<(), WalletLifecycleError> {
    validate_record_id(&descriptor.record_id)?;

    if descriptor.secret_ref != secret_ref_for(&descriptor.record_id)
        || TonAddress::from_str(&descriptor.address).is_err()
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

fn validate_record_id(record_id: &str) -> Result<(), WalletLifecycleError> {
    if record_id.is_empty()
        || record_id.len() > MAX_RECORD_ID_BYTES
        || !record_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err(WalletLifecycleError::InvalidRecordId);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    const ADDRESS: &str = "0:1111111111111111111111111111111111111111111111111111111111111111";

    #[test]
    fn descriptor_must_use_the_record_bound_secret_reference() {
        let descriptor = WalletDescriptor {
            record_id: "wallet-record".to_owned(),
            address: ADDRESS.to_owned(),
            network: Network::Testnet,
            secret_ref: ProtectedSecretRef {
                value: "wallet:another-record:mnemonic".to_owned(),
            },
        };

        assert_eq!(
            validate_descriptor(&descriptor),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }

    #[test]
    fn descriptor_rejects_an_invalid_wallet_address() {
        let record_id = "wallet-record";
        let descriptor = WalletDescriptor {
            record_id: record_id.to_owned(),
            address: "not-a-ton-address".to_owned(),
            network: Network::Testnet,
            secret_ref: secret_ref_for(record_id),
        };

        assert_eq!(
            validate_descriptor(&descriptor),
            Err(WalletLifecycleError::InvalidRecordId)
        );
    }
}
