//! HTTP requests, responses, and host callback errors.

use std::sync::Arc;

use async_trait::async_trait;
use serde_json::Value;

use crate::domain::bounded_diagnostic;
use crate::{DomainError, ErrorCategory, ErrorCode, RetryAdvice};

use super::ProviderTransport;

/// An HTTP method that the host must execute.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpMethod {
    /// An HTTP GET request.
    Get,
    /// An HTTP POST request.
    Post,
}

/// Correlation identity generated by Rust. Hosts can use it to bind their
/// native cancellation bookkeeping, but must not assign semantic meaning to
/// the numeric value.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Record,
)]
#[serde(rename_all = "camelCase")]
pub struct HttpRequestId {
    /// An opaque numeric value allocated by this client instance.
    pub value: u64,
}

/// One HTTP header name and value.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpHeader {
    /// The header name.
    pub name: String,
    /// The header value.
    pub value: String,
}

/// A complete HTTP request for the embedding language.
///
/// The host can add its Toncenter credential according to the actual request
/// URL and its local security policy. Redirects are forbidden.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpRequest {
    /// The identifier used for host cancellation.
    pub id: HttpRequestId,
    /// The request method.
    pub method: HttpMethod,
    /// The complete HTTPS request URL.
    pub url: String,
    /// The public request headers. Credential material is not present here.
    pub headers: Vec<HttpHeader>,
    /// The request body. GET requests use an empty body.
    pub body: Vec<u8>,
    /// End-to-end request timeout, in milliseconds.
    ///
    /// The host must enforce this deadline across connection setup, response
    /// headers, and response-body reads. Expiry is reported as
    /// [`HttpHostErrorKind::Timeout`].
    pub timeout_ms: u64,
}

/// The complete HTTP response returned by the host.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpResponse {
    /// The HTTP status code.
    pub status: u16,
    /// The response headers accepted by the host.
    pub headers: Vec<HttpHeader>,
    /// The response body accepted by the host.
    pub body: Vec<u8>,
    /// The final response URL reported by the host. It must equal the request URL
    /// because the engine does not permit redirects.
    pub final_url: String,
}

/// Classifies a failure reported by the HTTP host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostErrorKind {
    /// No network connection is available.
    Offline,
    /// The request exceeded a host timeout.
    Timeout,
    /// An established connection ended before completion.
    ConnectionLost,
    /// DNS resolution failed.
    Dns,
    /// TLS negotiation or certificate validation failed.
    Tls,
    /// The request violated a host security policy.
    PolicyViolation,
    /// The response exceeded a limit imposed by the host.
    ResponseTooLarge,
    /// The host cancelled the request.
    Cancelled,
    /// The failure does not match another kind.
    Other,
}

/// An HTTP failure returned by [`WalletHttpHost`].
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[uniffi::export(Display)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostError {
    /// Reports a classified host failure with a safe diagnostic message.
    #[error("HTTP host failure ({kind:?}): {diagnostic}")]
    Failed {
        /// The stable failure classification.
        kind: HttpHostErrorKind,
        /// A developer-facing message without secrets or credential values.
        diagnostic: String,
    },
}

/// Executes HTTP work for the engine.
///
/// The host must enforce the request timeout while it connects and reads the
/// response. It owns any local response limits, must reject redirects, and must
/// return the observed URL in `final_url`.
#[uniffi::export(foreign)]
#[async_trait]
pub trait WalletHttpHost: Send + Sync {
    /// Executes one complete HTTP request and returns an accepted response.
    ///
    /// The host can add its Toncenter credential according to the actual URL
    /// and its local security policy. It must return
    /// [`HttpHostErrorKind::Timeout`] when `request.timeout_ms` expires.
    async fn execute_http(&self, request: HttpRequest) -> Result<HttpResponse, HttpHostError>;

    /// Requests cancellation of the request with `request_id`.
    ///
    /// This callback must be idempotent. It can run before `execute_http`
    /// registers the request, so the host must remember an early cancellation.
    async fn cancel_http(&self, request_id: HttpRequestId);
}

/// Adapts the public HTTP host callback to the engine's provider transport boundary.
pub(crate) struct HttpTransport {
    host: Arc<dyn WalletHttpHost>,
}

impl HttpTransport {
    pub(crate) fn new(host: Arc<dyn WalletHttpHost>) -> Self {
        Self { host }
    }
}

#[async_trait]
impl ProviderTransport for HttpTransport {
    async fn execute(&self, request: &HttpRequest) -> Result<Vec<u8>, DomainError> {
        let result = self.host.execute_http(request.clone()).await;
        process_response(request, result)
    }

    async fn cancel(&self, request_id: HttpRequestId) {
        self.host.cancel_http(request_id).await;
    }
}

/// Maps host and provider failures, verifies the response origin, and returns the body.
fn process_response(
    request: &HttpRequest,
    result: Result<HttpResponse, HttpHostError>,
) -> Result<Vec<u8>, DomainError> {
    let response = match result {
        Ok(response) => response,
        Err(HttpHostError::Failed { kind, diagnostic }) => {
            return Err(host_error(kind, &diagnostic));
        }
    };

    // Native transports commonly follow redirects by default. Reject a truthful
    // host report when the response came from anywhere but the requested endpoint.
    if response.final_url != request.url {
        return Err(host_error(
            HttpHostErrorKind::PolicyViolation,
            "HTTP redirect or mismatched final URL",
        ));
    }

    if let Some(error) = response_error(response.status, &response.headers, &response.body) {
        return Err(error);
    }

    Ok(response.body)
}

fn host_error(kind: HttpHostErrorKind, message: &str) -> DomainError {
    let cancelled = kind == HttpHostErrorKind::Cancelled;
    let policy = kind == HttpHostErrorKind::PolicyViolation;
    let too_large = kind == HttpHostErrorKind::ResponseTooLarge;

    DomainError {
        code: if cancelled {
            ErrorCode::HostCancelled
        } else if policy {
            ErrorCode::HostPolicyViolation
        } else if too_large {
            ErrorCode::ResponseTooLarge
        } else {
            ErrorCode::TransportFailed
        },
        category: if cancelled {
            ErrorCategory::Cancellation
        } else if policy || too_large {
            ErrorCategory::HostPolicy
        } else {
            ErrorCategory::Transport
        },
        retry: if cancelled || policy || too_large {
            RetryAdvice::None
        } else {
            RetryAdvice::Safe
        },
        developer_message: bounded_diagnostic(message),
        provider_status: None,
        retry_after_ms: None,
        host_kind: Some(kind),
    }
}

fn response_error(status: u16, headers: &[HttpHeader], body: &[u8]) -> Option<DomainError> {
    if (200..300).contains(&status) {
        return None;
    }

    let developer_message = provider_message(body).unwrap_or_else(|| format!("HTTP {status}"));

    if status == 429 {
        let retry_after_ms = parse_retry_after_ms(headers);
        return Some(DomainError {
            code: ErrorCode::RateLimited,
            category: ErrorCategory::RateLimit,
            retry: if retry_after_ms.is_some() {
                RetryAdvice::AfterDelay
            } else {
                RetryAdvice::Safe
            },
            developer_message,
            provider_status: Some(status),
            retry_after_ms,
            host_kind: None,
        });
    }

    Some(DomainError {
        code: ErrorCode::HttpRejected,
        category: ErrorCategory::ProviderProtocol,
        retry: if status >= 500 {
            RetryAdvice::Safe
        } else {
            RetryAdvice::None
        },
        developer_message,
        provider_status: Some(status),
        retry_after_ms: None,
        host_kind: None,
    })
}

fn provider_message(body: &[u8]) -> Option<String> {
    let value: Value = serde_json::from_slice(body).ok()?;

    ["error", "description", "message"]
        .into_iter()
        .find_map(|field| value.get(field).and_then(Value::as_str))
        .map(bounded_diagnostic)
}

fn parse_retry_after_ms(headers: &[HttpHeader]) -> Option<u64> {
    let seconds = headers
        .iter()
        .find(|header| header.name.eq_ignore_ascii_case("retry-after"))?
        .value
        .trim()
        .parse::<u64>()
        .ok()?;

    seconds.checked_mul(1_000)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn request() -> HttpRequest {
        HttpRequest {
            id: HttpRequestId { value: 7 },
            method: HttpMethod::Get,
            url: "https://provider.example/api/v2/resource?limit=10".to_owned(),
            headers: Vec::new(),
            body: Vec::new(),
            timeout_ms: 15_000,
        }
    }

    fn response(request: &HttpRequest, body: &[u8]) -> HttpResponse {
        HttpResponse {
            status: 200,
            headers: Vec::new(),
            body: body.to_vec(),
            final_url: request.url.clone(),
        }
    }

    #[test]
    fn returns_the_body_of_a_successful_response() {
        let request = request();
        let body = process_response(&request, Ok(response(&request, b"wallet")))
            .expect("a successful response must expose its body");

        assert_eq!(body, b"wallet");
    }

    #[test]
    fn rejects_a_redirect_before_parsing_the_body() {
        let request = request();
        let mut redirected = response(&request, b"ignored");
        redirected.final_url = "https://attacker.example/response".to_owned();

        let error = process_response(&request, Ok(redirected))
            .expect_err("a changed final URL must be rejected");

        assert_eq!(error.code, ErrorCode::HostPolicyViolation);
        assert_eq!(error.category, ErrorCategory::HostPolicy);
        assert_eq!(error.retry, RetryAdvice::None);
        assert_eq!(error.host_kind, Some(HttpHostErrorKind::PolicyViolation));
        assert_eq!(
            error.developer_message,
            "HTTP redirect or mismatched final URL"
        );
    }

    #[test]
    fn maps_every_host_failure_family_to_a_stable_domain_error() {
        let cases = [
            (
                HttpHostErrorKind::Cancelled,
                ErrorCode::HostCancelled,
                ErrorCategory::Cancellation,
                RetryAdvice::None,
            ),
            (
                HttpHostErrorKind::PolicyViolation,
                ErrorCode::HostPolicyViolation,
                ErrorCategory::HostPolicy,
                RetryAdvice::None,
            ),
            (
                HttpHostErrorKind::ResponseTooLarge,
                ErrorCode::ResponseTooLarge,
                ErrorCategory::HostPolicy,
                RetryAdvice::None,
            ),
            (
                HttpHostErrorKind::Offline,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
            (
                HttpHostErrorKind::Timeout,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
            (
                HttpHostErrorKind::ConnectionLost,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
            (
                HttpHostErrorKind::Dns,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
            (
                HttpHostErrorKind::Tls,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
            (
                HttpHostErrorKind::Other,
                ErrorCode::TransportFailed,
                ErrorCategory::Transport,
                RetryAdvice::Safe,
            ),
        ];

        for (kind, code, category, retry) in cases {
            let request = request();
            let error = process_response(
                &request,
                Err(HttpHostError::Failed {
                    kind,
                    diagnostic: format!("{kind:?} diagnostic"),
                }),
            )
            .expect_err("a host error must not reach the parser");

            assert_eq!(error.code, code, "wrong code for {kind:?}");
            assert_eq!(error.category, category, "wrong category for {kind:?}");
            assert_eq!(error.retry, retry, "wrong retry advice for {kind:?}");
            assert_eq!(error.host_kind, Some(kind));
            assert_eq!(error.provider_status, None);
            assert_eq!(error.retry_after_ms, None);
        }
    }

    #[test]
    fn forwards_provider_rejections_before_parsing() {
        let request = request();
        let mut rejected = response(&request, br#"{"error":"denied"}"#);
        rejected.status = 403;

        let error = process_response(&request, Ok(rejected))
            .expect_err("a provider rejection must not reach the parser");

        assert_eq!(error.code, ErrorCode::HttpRejected);
        assert_eq!(error.category, ErrorCategory::ProviderProtocol);
        assert_eq!(error.provider_status, Some(403));
    }

    #[test]
    fn rate_limit_retry_after_is_converted_to_milliseconds() {
        let request = request();
        let mut rejected = response(&request, br#"{"error":"slow down"}"#);
        rejected.status = 429;
        rejected.headers.push(HttpHeader {
            name: "Retry-After".to_owned(),
            value: "7".to_owned(),
        });

        let error = process_response(&request, Ok(rejected))
            .expect_err("a rate limit must not reach the parser");

        assert_eq!(error.code, ErrorCode::RateLimited);
        assert_eq!(error.category, ErrorCategory::RateLimit);
        assert_eq!(error.retry, RetryAdvice::AfterDelay);
        assert_eq!(error.retry_after_ms, Some(7_000));
    }
}
