//! C representations of wallet lifecycle types.

use wallet_engine::{CreateWalletRequest, CreatedWallet, WalletDescriptor, WalletLifecycleError};

use crate::abi::{WalletEngineAbiStatus, WalletEngineStringView};

use super::{
    WALLET_ENGINE_PROTECTED_SECRET_HOST_ERROR_KIND_OTHER, WalletEngineNetwork,
    WalletEngineProtectedSecretHostErrorKind, WalletEngineProtectedSecretRefView, network_from_abi,
    network_to_abi, protected_secret_host_error_kind_to_abi,
};

/// A borrowed request to generate a new V5R1 wallet.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineCreateWalletRequest {
    /// Stable application identity, normally a UUID generated by the host.
    pub record_id: WalletEngineStringView,
    /// Network used to derive the wallet contract and address.
    pub network: WalletEngineNetwork,
}

impl WalletEngineCreateWalletRequest {
    /// Validates and copies this C request into the core domain type.
    ///
    /// # Errors
    ///
    /// Returns an ABI status when the record-ID view or network value is
    /// malformed. Domain validation of the record ID remains the responsibility
    /// of `WalletLifecycle::create_wallet`.
    ///
    /// # Safety
    ///
    /// When `record_id.data` is non-null and its length is accepted, it must
    /// remain readable for the duration of this call.
    pub unsafe fn try_to_core(self) -> Result<CreateWalletRequest, WalletEngineAbiStatus> {
        // SAFETY: The caller upholds the readable-range requirement documented
        // by this method. The string-view helper validates null and length.
        let record_id = unsafe { self.record_id.try_to_string()? };
        let network = network_from_abi(self.network)?;
        Ok(CreateWalletRequest { record_id, network })
    }
}

/// A borrowed sequence of UTF-8 string views.
///
/// `data` may be null only when `len` is zero. The elements and their strings
/// remain valid only for the duration of the callback receiving this view.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineStringViewSlice {
    /// Pointer to the first string view.
    pub data: *const WalletEngineStringView,
    /// Number of string views in the sequence.
    pub len: usize,
}

impl From<&[WalletEngineStringView]> for WalletEngineStringViewSlice {
    fn from(value: &[WalletEngineStringView]) -> Self {
        if value.is_empty() {
            return Self {
                data: std::ptr::null(),
                len: 0,
            };
        }

        Self {
            data: value.as_ptr(),
            len: value.len(),
        }
    }
}

/// Borrowed public wallet metadata that is safe for the application to retain
/// after copying it.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineWalletDescriptorView {
    /// Stable application record identifier.
    pub record_id: WalletEngineStringView,
    /// Friendly non-bounceable TON address.
    pub address: WalletEngineStringView,
    /// Network used for derivation and future operations.
    pub network: WalletEngineNetwork,
    /// Host protected-storage reference for the mnemonic.
    pub secret_ref: WalletEngineProtectedSecretRefView,
}

impl From<&WalletDescriptor> for WalletEngineWalletDescriptorView {
    fn from(value: &WalletDescriptor) -> Self {
        Self {
            record_id: WalletEngineStringView::from(value.record_id.as_str()),
            address: WalletEngineStringView::from(value.address.as_str()),
            network: network_to_abi(value.network),
            secret_ref: WalletEngineProtectedSecretRefView::from(&value.secret_ref),
        }
    }
}

/// A borrowed one-shot recovery phrase.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineRecoveryPhraseView {
    /// Recovery words in order. A successful creation contains exactly 24.
    pub words: WalletEngineStringViewSlice,
}

/// A borrowed result of creating a wallet.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineCreatedWalletView {
    /// Public metadata that the application must persist after copying.
    pub descriptor: WalletEngineWalletDescriptorView,
    /// Transient recovery phrase that must be discarded after presentation.
    pub recovery_phrase: WalletEngineRecoveryPhraseView,
}

/// Calls `callback` with a C view of a created wallet.
///
/// All pointers in the supplied view remain valid only until `callback`
/// returns.
pub fn with_created_wallet_view<R>(
    value: &CreatedWallet,
    callback: impl FnOnce(WalletEngineCreatedWalletView) -> R,
) -> R {
    let word_views = value
        .recovery_phrase
        .words
        .iter()
        .map(|word| WalletEngineStringView::from(word.as_str()))
        .collect::<Vec<_>>();
    let view = WalletEngineCreatedWalletView {
        descriptor: WalletEngineWalletDescriptorView::from(&value.descriptor),
        recovery_phrase: WalletEngineRecoveryPhraseView {
            words: WalletEngineStringViewSlice::from(word_views.as_slice()),
        },
    };
    callback(view)
}

/// Stable machine-readable wallet lifecycle failure code.
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WalletEngineWalletLifecycleErrorCode {
    /// The record ID is invalid.
    InvalidRecordId = 0,
    /// The recovery phrase is invalid.
    InvalidRecoveryPhrase = 1,
    /// Wallet address derivation failed.
    AddressDerivationFailed = 2,
    /// Protected recovery words belong to a different wallet.
    SecretWalletMismatch = 3,
    /// The protected-storage host reported a failure.
    ProtectedSecretHost = 4,
}

/// A borrowed wallet lifecycle failure.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct WalletEngineWalletLifecycleErrorView {
    /// Stable failure code.
    pub code: WalletEngineWalletLifecycleErrorCode,
    /// Whether `protected_secret_host_error_kind` contains a host failure.
    pub has_protected_secret_host_error_kind: bool,
    /// Protected-storage failure kind when the corresponding flag is true.
    pub protected_secret_host_error_kind: WalletEngineProtectedSecretHostErrorKind,
    /// Bounded diagnostic supplied by the protected-storage host, when present.
    pub diagnostic: WalletEngineStringView,
}

impl From<&WalletLifecycleError> for WalletEngineWalletLifecycleErrorView {
    fn from(value: &WalletLifecycleError) -> Self {
        let (code, host_kind, diagnostic) = match value {
            WalletLifecycleError::InvalidRecordId => (
                WalletEngineWalletLifecycleErrorCode::InvalidRecordId,
                None,
                None,
            ),
            WalletLifecycleError::InvalidRecoveryPhrase => (
                WalletEngineWalletLifecycleErrorCode::InvalidRecoveryPhrase,
                None,
                None,
            ),
            WalletLifecycleError::AddressDerivationFailed => (
                WalletEngineWalletLifecycleErrorCode::AddressDerivationFailed,
                None,
                None,
            ),
            WalletLifecycleError::SecretWalletMismatch => (
                WalletEngineWalletLifecycleErrorCode::SecretWalletMismatch,
                None,
                None,
            ),
            WalletLifecycleError::ProtectedSecretHost { kind, diagnostic } => (
                WalletEngineWalletLifecycleErrorCode::ProtectedSecretHost,
                Some(protected_secret_host_error_kind_to_abi(*kind)),
                Some(diagnostic.as_str()),
            ),
        };

        Self {
            code,
            has_protected_secret_host_error_kind: host_kind.is_some(),
            protected_secret_host_error_kind: host_kind
                .unwrap_or(WALLET_ENGINE_PROTECTED_SECRET_HOST_ERROR_KIND_OTHER),
            diagnostic: diagnostic
                .map_or_else(WalletEngineStringView::empty, WalletEngineStringView::from),
        }
    }
}
