#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, uniffi::Enum)]
pub enum NetworkV3 {
    Mainnet,
    Testnet,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct CredentialRefV3 {
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ProviderConfigV3 {
    pub toncenter_base_url: String,
    pub tonapi_base_url: String,
    pub toncenter_credential: Option<CredentialRefV3>,
    /// Normalized HTTPS origin allowed to receive `toncenter_credential`.
    /// It includes the effective port, for example
    /// `https://testnet.toncenter.com:443`.
    pub toncenter_credential_origin: Option<String>,
}

impl ProviderConfigV3 {
    #[must_use]
    pub fn standard(network: NetworkV3, credential: Option<CredentialRefV3>) -> Self {
        let toncenter_base_url = match network {
            NetworkV3::Mainnet => "https://toncenter.com/api/v2",
            NetworkV3::Testnet => "https://testnet.toncenter.com/api/v2",
        };
        let toncenter_credential_origin = credential.as_ref().map(|_| match network {
            NetworkV3::Mainnet => "https://toncenter.com:443".to_owned(),
            NetworkV3::Testnet => "https://testnet.toncenter.com:443".to_owned(),
        });
        Self {
            toncenter_base_url: toncenter_base_url.to_owned(),
            tonapi_base_url: "https://tonapi.io/v2".to_owned(),
            toncenter_credential: credential,
            toncenter_credential_origin,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct WalletClientConfigV3 {
    pub wallet_id: String,
    pub address: String,
    pub network: NetworkV3,
    pub providers: ProviderConfigV3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum HttpMethodV3 {
    Get,
    Post,
}

/// Correlation identity generated by Rust. Hosts may use it to bind their
/// native cancellation bookkeeping, but must not assign semantic meaning to
/// the numeric value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, uniffi::Record)]
pub struct HttpCallIdV3 {
    pub value: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct HttpHeaderV3 {
    pub name: String,
    pub value: String,
}

/// A complete, bounded HTTP invocation for the embedding language.
///
/// The host resolves `credential` locally and must inject it only when the
/// request origin exactly equals `credential_origin`. Redirects are forbidden.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct HttpCall {
    pub id: HttpCallIdV3,
    pub method: HttpMethodV3,
    pub url: String,
    pub headers: Vec<HttpHeaderV3>,
    pub body: Vec<u8>,
    pub credential: Option<CredentialRefV3>,
    pub credential_origin: Option<String>,
    pub max_response_header_bytes: u64,
    pub max_response_body_bytes: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct HttpResponse {
    pub status: u16,
    pub headers: Vec<HttpHeaderV3>,
    pub body: Vec<u8>,
    /// The final response URL reported by the host. It must equal the call URL
    /// because V3 does not permit redirects.
    pub final_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum HttpHostErrorKind {
    Offline,
    Timeout,
    ConnectionLost,
    Dns,
    Tls,
    PolicyViolation,
    ResponseTooLarge,
    Cancelled,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error, uniffi::Error)]
pub enum HttpHostError {
    #[error("HTTP host failure ({kind:?}): {message}")]
    Failed {
        kind: HttpHostErrorKind,
        message: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum AccountStatusV3 {
    Nonexistent,
    Uninitialized,
    Active,
    Frozen,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct AccountSnapshotV3 {
    pub balance_nanograms: String,
    pub balance_grams: String,
    pub status: AccountStatusV3,
    pub sync_utime: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ActivityDirectionV3 {
    Sent,
    Received,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ActivityItemV3 {
    pub id: String,
    pub transaction_hash: String,
    pub logical_time: String,
    pub timestamp: u64,
    pub direction: ActivityDirectionV3,
    pub amount_nanograms: String,
    pub amount_grams: String,
    pub counterparty: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ActivityCursorV3 {
    pub logical_time: String,
    pub hash: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ResourcePhaseV3 {
    Idle,
    Loading,
    Ready,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ResourceStateV3 {
    pub phase: ResourcePhaseV3,
    pub error: Option<DomainErrorV3>,
}

impl ResourceStateV3 {
    pub(crate) const fn idle() -> Self {
        Self {
            phase: ResourcePhaseV3::Idle,
            error: None,
        }
    }

    pub(crate) const fn loading() -> Self {
        Self {
            phase: ResourcePhaseV3::Loading,
            error: None,
        }
    }

    pub(crate) const fn ready() -> Self {
        Self {
            phase: ResourcePhaseV3::Ready,
            error: None,
        }
    }

    pub(crate) const fn failed(error: DomainErrorV3) -> Self {
        Self {
            phase: ResourcePhaseV3::Failed,
            error: Some(error),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ErrorCategoryV3 {
    Transport,
    ProviderProtocol,
    RateLimit,
    Cancellation,
    HostPolicy,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ErrorCodeV3 {
    InvalidProviderResponse,
    HttpRejected,
    RateLimited,
    TransportFailed,
    HostCancelled,
    ResponseTooLarge,
    HostPolicyViolation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum RetryAdviceV3 {
    None,
    Safe,
    AfterDelay,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct DomainErrorV3 {
    pub code: ErrorCodeV3,
    pub category: ErrorCategoryV3,
    pub retry: RetryAdviceV3,
    pub developer_message: String,
    pub provider_status: Option<u16>,
    pub retry_after_ms: Option<u64>,
    pub host_kind: Option<HttpHostErrorKind>,
}

#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct WalletSnapshotV3 {
    pub revision: u64,
    pub wallet_id: String,
    pub address: String,
    pub network: NetworkV3,
    pub account: Option<AccountSnapshotV3>,
    pub account_resource: ResourceStateV3,
    pub activity: Vec<ActivityItemV3>,
    pub activity_resource: ResourceStateV3,
    pub activity_pagination_resource: ResourceStateV3,
    pub activity_cursor: Option<ActivityCursorV3>,
    pub activity_has_more: bool,
    pub usd_per_gram: Option<f64>,
    pub rate_resource: ResourceStateV3,
    pub send: SendSnapshotV3,
}

impl WalletSnapshotV3 {
    pub(crate) fn empty(config: &WalletClientConfigV3) -> Self {
        Self {
            revision: 0,
            wallet_id: config.wallet_id.clone(),
            address: config.address.clone(),
            network: config.network,
            account: None,
            account_resource: ResourceStateV3::idle(),
            activity: Vec::new(),
            activity_resource: ResourceStateV3::idle(),
            activity_pagination_resource: ResourceStateV3::idle(),
            activity_cursor: None,
            activity_has_more: false,
            usd_per_gram: None,
            rate_resource: ResourceStateV3::idle(),
            send: SendSnapshotV3 {
                operation_id: None,
                phase: SendPhaseV3::Idle,
                error_message: None,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum WalletOperationOutcomeV3 {
    Completed,
    PartiallyCompleted,
    Failed,
    Cancelled,
    Superseded,
    Skipped,
}

#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct WalletUpdateV3 {
    pub outcome: WalletOperationOutcomeV3,
    pub activity_items_added: u64,
    pub snapshot: WalletSnapshotV3,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error, uniffi::Error)]
pub enum WalletClientErrorV3 {
    #[error("invalid V3 wallet client configuration")]
    InvalidConfig,
    #[error("V3 wallet client identifier space is exhausted")]
    IdentifierExhausted,
    #[error("V3 wallet client state is unavailable")]
    StateUnavailable,
    #[error("the send has crossed its durable commit boundary and can no longer be cancelled")]
    SendCancellationTooLate,
    #[error("V3 wallet client is shut down")]
    Shutdown,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ProtectedSecretRefV3 {
    pub value: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum SecretAccessReasonV3 {
    CreateWallet,
    SignTransfer,
    RevealRecoveryPhrase,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ProtectedSecretReadV3 {
    pub secret_ref: ProtectedSecretRefV3,
    pub reason: SecretAccessReasonV3,
    pub prompt: String,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ProtectedSecretStoreV3 {
    pub secret_ref: ProtectedSecretRefV3,
    pub bytes: Vec<u8>,
    pub require_user_presence: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ProtectedSecretHostErrorKindV3 {
    NotFound,
    AuthenticationFailed,
    Cancelled,
    Unavailable,
    PolicyViolation,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error, uniffi::Error)]
pub enum ProtectedSecretHostErrorV3 {
    #[error("protected-secret host failure ({kind:?}): {message}")]
    Failed {
        kind: ProtectedSecretHostErrorKindV3,
        message: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct JournalKeyV3 {
    pub wallet_id: String,
    pub slot: String,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct JournalRecordV3 {
    pub version: u64,
    pub payload: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct JournalCompareExchangeV3 {
    pub key: JournalKeyV3,
    pub expected_version: Option<u64>,
    pub replacement: JournalRecordV3,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct JournalCompareExchangeResultV3 {
    pub applied: bool,
    pub current: Option<JournalRecordV3>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum JournalHostErrorKindV3 {
    Unavailable,
    CorruptData,
    Cancelled,
    Other,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error, uniffi::Error)]
pub enum JournalHostErrorV3 {
    #[error("journal host failure ({kind:?}): {message}")]
    Failed {
        kind: JournalHostErrorKindV3,
        message: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SendRequestV3 {
    pub operation_id: String,
    pub destination: String,
    pub amount_nanograms: String,
    pub secret_ref: ProtectedSecretRefV3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum SendPhaseV3 {
    Idle,
    Validating,
    Authorizing,
    Preparing,
    Persisting,
    ReadyToSubmit,
    Submitting,
    SubmissionUnknown,
    Submitted,
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SendSnapshotV3 {
    pub operation_id: Option<String>,
    pub phase: SendPhaseV3,
    pub error_message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct PreparedSendV3 {
    pub operation_id: String,
    pub valid_until: u64,
    pub destination: String,
    pub amount_nanograms: String,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SendResultV3 {
    pub operation_id: String,
    pub message_hash: String,
    pub phase: SendPhaseV3,
}
