//! Public records, enums, and errors shared by the engine and host callbacks.
//!
//! `UniFFI` and WASM bindings expose these values to Swift, Kotlin, and
//! TypeScript. Records are immutable snapshots at the API boundary.

/// Selects the TON network used for addresses, providers, and wallet derivation.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Enum,
)]
#[serde(rename_all = "camelCase")]
pub enum Network {
    /// The production TON network.
    Mainnet,
    /// The public TON test network.
    Testnet,
}

/// An opaque reference to an HTTP credential stored by the host.
///
/// The value identifies a credential. It never contains the credential itself.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CredentialRef {
    /// The host-defined lookup key for the credential.
    pub value: String,
}

/// Configures the Toncenter endpoint and its optional host-owned credential.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfig {
    /// The HTTPS base URL for Toncenter API v2 calls.
    pub toncenter_base_url: String,
    /// The optional reference that the HTTP host resolves before a request.
    pub toncenter_credential: Option<CredentialRef>,
    /// Normalized HTTPS origin allowed to receive `toncenter_credential`.
    /// It includes the effective port, for example
    /// `https://testnet.toncenter.com:443`.
    pub toncenter_credential_origin: Option<String>,
}

impl ProviderConfig {
    /// Returns the standard Toncenter configuration for `network`.
    ///
    /// The credential origin includes the effective HTTPS port. The host must
    /// compare this origin exactly before it adds the credential.
    #[must_use]
    pub fn standard(network: Network, credential: Option<CredentialRef>) -> Self {
        let toncenter_base_url = match network {
            Network::Mainnet => "https://toncenter.com/api/v2",
            Network::Testnet => "https://testnet.toncenter.com/api/v2",
        };
        let toncenter_credential_origin = credential.as_ref().map(|_| match network {
            Network::Mainnet => "https://toncenter.com:443".to_owned(),
            Network::Testnet => "https://testnet.toncenter.com:443".to_owned(),
        });
        Self {
            toncenter_base_url: toncenter_base_url.to_owned(),
            toncenter_credential: credential,
            toncenter_credential_origin,
        }
    }
}

/// Identifies one wallet client and its provider configuration.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletClientConfig {
    /// The stable application record identifier for this wallet.
    pub record_id: String,
    /// The friendly TON address that the client reads and sends from.
    pub address: String,
    /// The network for the address and all provider calls.
    pub network: Network,
    /// The provider endpoints and credential references.
    pub providers: ProviderConfig,
}

/// An HTTP method that the host must execute.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpMethod {
    /// An HTTP GET request.
    Get,
    /// An HTTP POST request.
    Post,
}

/// Correlation identity generated by Rust. Hosts can use it to bind their
/// native cancellation bookkeeping, but must not assign semantic meaning to
/// the numeric value.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Record,
)]
#[serde(rename_all = "camelCase")]
pub struct HttpCallId {
    /// An opaque numeric value allocated by this client instance.
    pub value: u64,
}

/// One HTTP header name and value.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpHeader {
    /// The header name.
    pub name: String,
    /// The header value.
    pub value: String,
}

/// A complete, bounded HTTP invocation for the embedding language.
///
/// The host resolves `credential` locally and must inject it only when the
/// request origin exactly equals `credential_origin`. Redirects are forbidden.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpCall {
    /// The identifier used for host cancellation.
    pub id: HttpCallId,
    /// The request method.
    pub method: HttpMethod,
    /// The complete HTTPS request URL.
    pub url: String,
    /// The public request headers. Credential material is not present here.
    pub headers: Vec<HttpHeader>,
    /// The request body. GET requests use an empty body.
    pub body: Vec<u8>,
    /// The optional host-owned credential reference.
    pub credential: Option<CredentialRef>,
    /// The exact HTTPS origin that can receive the credential.
    pub credential_origin: Option<String>,
    /// The maximum total response-header size accepted by Rust.
    pub max_response_header_bytes: u64,
    /// The maximum response-body size accepted by Rust.
    pub max_response_body_bytes: u64,
}

/// The complete bounded HTTP response returned by the host.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpResponse {
    /// The HTTP status code.
    pub status: u16,
    /// The response headers that fit within the requested limit.
    pub headers: Vec<HttpHeader>,
    /// The response body that fits within the requested limit.
    pub body: Vec<u8>,
    /// The final response URL reported by the host. It must equal the call URL
    /// because the engine does not permit redirects.
    pub final_url: String,
}

/// Classifies a failure reported by the HTTP host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostErrorKind {
    /// No network connection is available.
    Offline,
    /// The request exceeded a host timeout.
    Timeout,
    /// An established connection ended before completion.
    ConnectionLost,
    /// DNS resolution failed.
    Dns,
    /// TLS negotiation or certificate validation failed.
    Tls,
    /// The request violated a host security policy.
    PolicyViolation,
    /// The response exceeded a limit in [`HttpCall`].
    ResponseTooLarge,
    /// The host cancelled the call.
    Cancelled,
    /// The failure does not match another kind.
    Other,
}

/// An HTTP failure returned by [`crate::WalletHttpHost`].
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostError {
    /// Reports a classified host failure with a safe diagnostic message.
    #[error("HTTP host failure ({kind:?}): {diagnostic}")]
    Failed {
        /// The stable failure classification.
        kind: HttpHostErrorKind,
        /// A developer-facing message without secrets or credential values.
        diagnostic: String,
    },
}

/// The lifecycle state of a TON account.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum AccountStatus {
    /// No account exists at the address.
    Nonexistent,
    /// The account exists but its contract state is not initialized.
    Uninitialized,
    /// The account contract is active.
    Active,
    /// The account contract is frozen.
    Frozen,
    /// The provider returned an unrecognized account state.
    Unknown,
}

/// The latest parsed balance and status for a wallet account.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct AccountSnapshot {
    /// The exact unsigned balance in nanograms.
    pub balance_nanograms: String,
    /// The same balance formatted in grams without insignificant zeroes.
    pub balance_grams: String,
    /// The account lifecycle state.
    pub status: AccountStatus,
    /// The provider synchronization time as a Unix timestamp, if available.
    pub sync_utime: Option<u64>,
}

/// The value flow direction for one activity item.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ActivityDirection {
    /// Value left the wallet.
    Sent,
    /// Value entered the wallet.
    Received,
}

/// One nonzero incoming or outgoing value transfer in wallet activity.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ActivityItem {
    /// A stable item key derived from the transaction, direction, and message index.
    pub id: String,
    /// The canonical base64 transaction hash when the provider supplies one.
    pub transaction_hash: String,
    /// The transaction logical time as an unsigned decimal string.
    pub logical_time: String,
    /// The transaction Unix timestamp.
    pub timestamp: u64,
    /// The value flow direction relative to this wallet.
    pub direction: ActivityDirection,
    /// The exact transferred value in nanograms.
    pub amount_nanograms: String,
    /// The same value formatted in grams without insignificant zeroes.
    pub amount_grams: String,
    /// The source or destination address, if the provider supplies it.
    pub counterparty: Option<String>,
}

/// The provider cursor for the next older activity page.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ActivityCursor {
    /// The oldest loaded transaction logical time as an unsigned decimal string.
    pub logical_time: String,
    /// The oldest loaded transaction hash.
    pub hash: String,
}

/// The current state of one independently loaded resource.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ResourcePhase {
    /// No load is active and no successful value is available yet.
    Idle,
    /// A load is active.
    Loading,
    /// The latest load for this resource succeeded.
    Ready,
    /// The latest load for this resource failed.
    Failed,
}

/// A resource phase and its optional failure details.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ResourceState {
    /// The current resource phase.
    pub phase: ResourcePhase,
    /// The last error. This value is present only for [`ResourcePhase::Failed`].
    pub error: Option<DomainError>,
}

impl ResourceState {
    pub(crate) const fn idle() -> Self {
        Self {
            phase: ResourcePhase::Idle,
            error: None,
        }
    }

    pub(crate) const fn loading() -> Self {
        Self {
            phase: ResourcePhase::Loading,
            error: None,
        }
    }

    pub(crate) const fn ready() -> Self {
        Self {
            phase: ResourcePhase::Ready,
            error: None,
        }
    }

    pub(crate) const fn failed(error: DomainError) -> Self {
        Self {
            phase: ResourcePhase::Failed,
            error: Some(error),
        }
    }
}

/// The broad source of a provider or host error.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCategory {
    /// Network transport failed.
    Transport,
    /// The provider rejected a request or returned invalid data.
    ProviderProtocol,
    /// The provider applied a request limit.
    RateLimit,
    /// The host cancelled the request.
    Cancellation,
    /// The host rejected the request because of a security or size policy.
    HostPolicy,
}

/// A stable machine-readable domain error code.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCode {
    /// The provider response did not match the expected schema.
    InvalidProviderResponse,
    /// The provider returned an HTTP or protocol rejection.
    HttpRejected,
    /// The provider applied a request limit.
    RateLimited,
    /// The host reported a transport failure.
    TransportFailed,
    /// The host cancelled the request.
    HostCancelled,
    /// The response exceeded a configured bound.
    ResponseTooLarge,
    /// The request violated a host security policy.
    HostPolicyViolation,
}

/// States whether the same operation can be retried safely.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum RetryAdvice {
    /// Do not retry the operation without a user or configuration change.
    None,
    /// The same read-only operation can be retried.
    Safe,
    /// Retry after [`DomainError::retry_after_ms`].
    AfterDelay,
}

/// Structured error data for account and activity resources.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct DomainError {
    /// The stable machine-readable code.
    pub code: ErrorCode,
    /// The broad source of the error.
    pub category: ErrorCategory,
    /// Retry guidance for the failed operation.
    pub retry: RetryAdvice,
    /// A sanitized developer-facing diagnostic with a bounded length.
    pub developer_message: String,
    /// The provider status code, if the provider returned one.
    pub provider_status: Option<u16>,
    /// The provider delay in milliseconds, if it returned a numeric `Retry-After` header.
    pub retry_after_ms: Option<u64>,
    /// The original host failure kind, if the error came from a callback.
    pub host_kind: Option<HttpHostErrorKind>,
}

/// An immutable view of all observable state in one wallet client.
///
/// Each published change increments `revision`. A failed refresh preserves
/// the last successful resource value and changes its resource state.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletSnapshot {
    /// A client-local counter that increases for every published state change.
    pub revision: u64,
    /// The stable application record identifier.
    pub record_id: String,
    /// The wallet address.
    pub address: String,
    /// The wallet network.
    pub network: Network,
    /// The latest successful account value, if available.
    pub account: Option<AccountSnapshot>,
    /// The load state for `account`.
    pub account_resource: ResourceState,
    /// Activity in descending logical-time order with duplicate items removed.
    pub activity: Vec<ActivityItem>,
    /// The load state for the first activity page.
    pub activity_resource: ResourceState,
    /// The load state for an additional activity page.
    pub activity_pagination_resource: ResourceState,
    /// The cursor for the next older activity page.
    pub activity_cursor: Option<ActivityCursor>,
    /// Whether the provider can have another activity page.
    pub activity_has_more: bool,
    /// The current transfer workflow state.
    pub send: SendSnapshot,
}

impl WalletSnapshot {
    pub(crate) fn empty(config: &WalletClientConfig) -> Self {
        Self {
            revision: 0,
            record_id: config.record_id.clone(),
            address: config.address.clone(),
            network: config.network,
            account: None,
            account_resource: ResourceState::idle(),
            activity: Vec::new(),
            activity_resource: ResourceState::idle(),
            activity_pagination_resource: ResourceState::idle(),
            activity_cursor: None,
            activity_has_more: false,
            send: SendSnapshot {
                operation_id: None,
                phase: SendPhase::Idle,
                error_message: None,
            },
        }
    }
}

/// The terminal result of a wallet client operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum WalletOperationOutcome {
    /// All requested resources completed successfully.
    Completed,
    /// Some refresh resources succeeded and some failed.
    PartiallyCompleted,
    /// The requested operation failed.
    Failed,
    /// The host or caller cancelled the operation.
    Cancelled,
    /// A newer operation replaced this operation before publication completed.
    Superseded,
    /// Preconditions did not permit work, so the client made no request.
    Skipped,
}

/// The result of a refresh or pagination call and its resulting snapshot.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletUpdate {
    /// The terminal operation outcome.
    pub outcome: WalletOperationOutcome,
    /// The number of new unique activity items added by pagination.
    pub activity_items_added: u64,
    /// The immutable snapshot after the operation.
    pub snapshot: WalletSnapshot,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
/// An operational failure returned by [`crate::WalletClient`].
pub enum WalletClientError {
    /// The client configuration or operation request is invalid.
    #[error("invalid  wallet client configuration")]
    InvalidConfig,
    /// A client-local identifier or revision counter overflowed.
    #[error(" wallet client identifier space is exhausted")]
    IdentifierExhausted,
    /// The internal state lock or active operation state is unavailable.
    #[error(" wallet client state is unavailable")]
    StateUnavailable,
    /// A send crossed its durable commit boundary and cannot be cancelled.
    #[error("the send has crossed its durable commit boundary and can no longer be cancelled")]
    SendCancellationTooLate,
    /// The client is shut down and accepts no new work.
    #[error(" wallet client is shut down")]
    Shutdown,
}

/// An opaque reference to recovery words in host protected storage.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretRef {
    /// The host storage key. The value does not contain secret bytes.
    pub value: String,
}

/// Explains why the engine requests access to a protected secret.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum SecretAccessReason {
    /// Reserved for wallet creation storage policy.
    CreateWallet,
    /// The engine needs the mnemonic to sign a transfer.
    SignTransfer,
    /// The user requested the recovery phrase.
    RevealRecoveryPhrase,
}

/// A request to read and authorize access to protected secret bytes.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretRead {
    /// The host storage key.
    pub secret_ref: ProtectedSecretRef,
    /// The operation that needs secret access.
    pub reason: SecretAccessReason,
    /// User-facing authentication text supplied by Rust.
    pub prompt: String,
}

/// A request to store secret bytes in platform protected storage.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretStore {
    /// The host storage key.
    pub secret_ref: ProtectedSecretRef,
    /// The mnemonic bytes. The host must not log or persist them outside protected storage.
    pub bytes: Vec<u8>,
    /// Whether later reads must require user presence or device authentication.
    pub require_user_presence: bool,
}

/// Classifies a protected-storage failure reported by the host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ProtectedSecretHostErrorKind {
    /// No secret exists for the reference.
    NotFound,
    /// User or device authentication failed.
    AuthenticationFailed,
    /// The user or host cancelled the operation.
    Cancelled,
    /// Protected storage is temporarily unavailable.
    Unavailable,
    /// The request violates a platform security policy.
    PolicyViolation,
    /// The failure does not match another kind.
    Other,
}

/// A protected-storage failure returned by [`crate::WalletPlatformHost`].
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum ProtectedSecretHostError {
    /// Reports a classified host failure with a safe diagnostic message.
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    Failed {
        /// The stable failure classification.
        kind: ProtectedSecretHostErrorKind,
        /// A developer-facing message that contains no secret bytes.
        diagnostic: String,
    },
}

/// Selects one durable journal slot for one wallet record.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalKey {
    /// The stable application record identifier.
    pub record_id: String,
    /// The engine-defined slot name.
    pub slot: String,
}

/// One opaque versioned journal value owned by the engine.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalRecord {
    /// The positive compare-and-swap version.
    pub version: u64,
    /// The opaque engine payload. The host must preserve these bytes exactly.
    pub payload: Vec<u8>,
}

/// An atomic compare-and-swap request for a journal slot.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalCompareExchange {
    /// The journal slot to change.
    pub key: JournalKey,
    /// The required current version, or `None` when the slot must be absent.
    pub expected_version: Option<u64>,
    /// The complete replacement value.
    pub replacement: JournalRecord,
}

/// The result of an atomic journal compare-and-swap operation.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalCompareExchangeResult {
    /// Whether the host stored the replacement.
    pub applied: bool,
    /// The current record after the operation, if one exists.
    pub current: Option<JournalRecord>,
}

/// Classifies a durable journal failure reported by the host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum JournalHostErrorKind {
    /// Durable storage is temporarily unavailable.
    Unavailable,
    /// The stored record cannot be read without data loss.
    CorruptData,
    /// The host cancelled the storage operation.
    Cancelled,
    /// The failure does not match another kind.
    Other,
}

/// A durable journal failure returned by [`crate::WalletPlatformHost`].
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum JournalHostError {
    /// Reports a classified journal failure with a safe diagnostic message.
    #[error("journal host failure ({kind:?}): {diagnostic}")]
    Failed {
        /// The stable failure classification.
        kind: JournalHostErrorKind,
        /// A developer-facing message that contains no secret or payload bytes.
        diagnostic: String,
    },
}

/// Requests one signed V5R1 transfer.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendRequest {
    /// A unique idempotency identifier chosen by the application.
    pub operation_id: String,
    /// A friendly or raw TON destination address.
    pub destination: String,
    /// A positive canonical unsigned amount in nanograms.
    pub amount_nanograms: String,
    /// The protected mnemonic reference for the source wallet.
    pub secret_ref: ProtectedSecretRef,
}

/// The public phase of the current or last send workflow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum SendPhase {
    /// No send has started.
    Idle,
    /// The engine validates the request, journal, and chain state.
    Validating,
    /// The host authorizes protected-secret access.
    Authorizing,
    /// Rust constructs and signs the transfer.
    Preparing,
    /// The host writes a durable journal record.
    Persisting,
    /// The exact signed BOC is durable and ready for submission.
    ReadyToSubmit,
    /// The HTTP host submits the signed BOC.
    Submitting,
    /// Submission can have succeeded, but the engine has no definite response.
    SubmissionUnknown,
    /// The provider accepted the signed BOC.
    Submitted,
    /// The send failed before an ambiguous submission result.
    Failed,
    /// The send was cancelled before its durable commit boundary.
    Cancelled,
}

/// The observable state of the send workflow.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendSnapshot {
    /// The active or last operation identifier, if a send started.
    pub operation_id: Option<String>,
    /// The current public phase.
    pub phase: SendPhase,
    /// A sanitized diagnostic for failed or unknown submission states.
    pub error_message: Option<String>,
}

/// A public summary of a signed transfer before submission.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct PreparedSend {
    /// The application operation identifier.
    pub operation_id: String,
    /// The Unix timestamp after which validators reject the transfer.
    pub valid_until: u64,
    /// The destination TON address.
    pub destination: String,
    /// The exact transfer amount in nanograms.
    pub amount_nanograms: String,
}

/// The result returned after the send workflow reaches a terminal phase.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendResult {
    /// The application operation identifier.
    pub operation_id: String,
    /// The canonical base64 hash of the signed external message.
    pub message_hash: String,
    /// The terminal phase. This can be [`SendPhase::SubmissionUnknown`].
    pub phase: SendPhase,
}
