#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Enum,
)]
#[serde(rename_all = "camelCase")]
pub enum Network {
    Mainnet,
    Testnet,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CredentialRef {
    pub value: String,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProviderConfig {
    pub toncenter_base_url: String,
    pub toncenter_credential: Option<CredentialRef>,
    /// Normalized HTTPS origin allowed to receive `toncenter_credential`.
    /// It includes the effective port, for example
    /// `https://testnet.toncenter.com:443`.
    pub toncenter_credential_origin: Option<String>,
}

impl ProviderConfig {
    #[must_use]
    pub fn standard(network: Network, credential: Option<CredentialRef>) -> Self {
        let toncenter_base_url = match network {
            Network::Mainnet => "https://toncenter.com/api/v2",
            Network::Testnet => "https://testnet.toncenter.com/api/v2",
        };
        let toncenter_credential_origin = credential.as_ref().map(|_| match network {
            Network::Mainnet => "https://toncenter.com:443".to_owned(),
            Network::Testnet => "https://testnet.toncenter.com:443".to_owned(),
        });
        Self {
            toncenter_base_url: toncenter_base_url.to_owned(),
            toncenter_credential: credential,
            toncenter_credential_origin,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletClientConfig {
    pub wallet_id: String,
    pub address: String,
    pub network: Network,
    pub providers: ProviderConfig,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpMethod {
    Get,
    Post,
}

/// Correlation identity generated by Rust. Hosts may use it to bind their
/// native cancellation bookkeeping, but must not assign semantic meaning to
/// the numeric value.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize, uniffi::Record,
)]
#[serde(rename_all = "camelCase")]
pub struct HttpCallId {
    pub value: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpHeader {
    pub name: String,
    pub value: String,
}

/// A complete, bounded HTTP invocation for the embedding language.
///
/// The host resolves `credential` locally and must inject it only when the
/// request origin exactly equals `credential_origin`. Redirects are forbidden.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpCall {
    pub id: HttpCallId,
    pub method: HttpMethod,
    pub url: String,
    pub headers: Vec<HttpHeader>,
    pub body: Vec<u8>,
    pub credential: Option<CredentialRef>,
    pub credential_origin: Option<String>,
    pub max_response_header_bytes: u64,
    pub max_response_body_bytes: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct HttpResponse {
    pub status: u16,
    pub headers: Vec<HttpHeader>,
    pub body: Vec<u8>,
    /// The final response URL reported by the host. It must equal the call URL
    /// because  does not permit redirects.
    pub final_url: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostErrorKind {
    Offline,
    Timeout,
    ConnectionLost,
    Dns,
    Tls,
    PolicyViolation,
    ResponseTooLarge,
    Cancelled,
    Other,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum HttpHostError {
    #[error("HTTP host failure ({kind:?}): {diagnostic}")]
    Failed {
        kind: HttpHostErrorKind,
        diagnostic: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum AccountStatus {
    Nonexistent,
    Uninitialized,
    Active,
    Frozen,
    Unknown,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct AccountSnapshot {
    pub balance_nanograms: String,
    pub balance_grams: String,
    pub status: AccountStatus,
    pub sync_utime: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ActivityDirection {
    Sent,
    Received,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ActivityItem {
    pub id: String,
    pub transaction_hash: String,
    pub logical_time: String,
    pub timestamp: u64,
    pub direction: ActivityDirection,
    pub amount_nanograms: String,
    pub amount_grams: String,
    pub counterparty: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ActivityCursor {
    pub logical_time: String,
    pub hash: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ResourcePhase {
    Idle,
    Loading,
    Ready,
    Failed,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ResourceState {
    pub phase: ResourcePhase,
    pub error: Option<DomainError>,
}

impl ResourceState {
    pub(crate) const fn idle() -> Self {
        Self {
            phase: ResourcePhase::Idle,
            error: None,
        }
    }

    pub(crate) const fn loading() -> Self {
        Self {
            phase: ResourcePhase::Loading,
            error: None,
        }
    }

    pub(crate) const fn ready() -> Self {
        Self {
            phase: ResourcePhase::Ready,
            error: None,
        }
    }

    pub(crate) const fn failed(error: DomainError) -> Self {
        Self {
            phase: ResourcePhase::Failed,
            error: Some(error),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCategory {
    Transport,
    ProviderProtocol,
    RateLimit,
    Cancellation,
    HostPolicy,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ErrorCode {
    InvalidProviderResponse,
    HttpRejected,
    RateLimited,
    TransportFailed,
    HostCancelled,
    ResponseTooLarge,
    HostPolicyViolation,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum RetryAdvice {
    None,
    Safe,
    AfterDelay,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct DomainError {
    pub code: ErrorCode,
    pub category: ErrorCategory,
    pub retry: RetryAdvice,
    pub developer_message: String,
    pub provider_status: Option<u16>,
    pub retry_after_ms: Option<u64>,
    pub host_kind: Option<HttpHostErrorKind>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletSnapshot {
    pub revision: u64,
    pub wallet_id: String,
    pub address: String,
    pub network: Network,
    pub account: Option<AccountSnapshot>,
    pub account_resource: ResourceState,
    pub activity: Vec<ActivityItem>,
    pub activity_resource: ResourceState,
    pub activity_pagination_resource: ResourceState,
    pub activity_cursor: Option<ActivityCursor>,
    pub activity_has_more: bool,
    pub send: SendSnapshot,
}

impl WalletSnapshot {
    pub(crate) fn empty(config: &WalletClientConfig) -> Self {
        Self {
            revision: 0,
            wallet_id: config.wallet_id.clone(),
            address: config.address.clone(),
            network: config.network,
            account: None,
            account_resource: ResourceState::idle(),
            activity: Vec::new(),
            activity_resource: ResourceState::idle(),
            activity_pagination_resource: ResourceState::idle(),
            activity_cursor: None,
            activity_has_more: false,
            send: SendSnapshot {
                operation_id: None,
                phase: SendPhase::Idle,
                error_message: None,
            },
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum WalletOperationOutcome {
    Completed,
    PartiallyCompleted,
    Failed,
    Cancelled,
    Superseded,
    Skipped,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletUpdate {
    pub outcome: WalletOperationOutcome,
    pub activity_items_added: u64,
    pub snapshot: WalletSnapshot,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum WalletClientError {
    #[error("invalid  wallet client configuration")]
    InvalidConfig,
    #[error(" wallet client identifier space is exhausted")]
    IdentifierExhausted,
    #[error(" wallet client state is unavailable")]
    StateUnavailable,
    #[error("the send has crossed its durable commit boundary and can no longer be cancelled")]
    SendCancellationTooLate,
    #[error(" wallet client is shut down")]
    Shutdown,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretRef {
    pub value: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum SecretAccessReason {
    CreateWallet,
    SignTransfer,
    RevealRecoveryPhrase,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretRead {
    pub secret_ref: ProtectedSecretRef,
    pub reason: SecretAccessReason,
    pub prompt: String,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ProtectedSecretStore {
    pub secret_ref: ProtectedSecretRef,
    pub bytes: Vec<u8>,
    pub require_user_presence: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum ProtectedSecretHostErrorKind {
    NotFound,
    AuthenticationFailed,
    Cancelled,
    Unavailable,
    PolicyViolation,
    Other,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum ProtectedSecretHostError {
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    Failed {
        kind: ProtectedSecretHostErrorKind,
        diagnostic: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalKey {
    pub wallet_id: String,
    pub slot: String,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalRecord {
    pub version: u64,
    pub payload: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalCompareExchange {
    pub key: JournalKey,
    pub expected_version: Option<u64>,
    pub replacement: JournalRecord,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct JournalCompareExchangeResult {
    pub applied: bool,
    pub current: Option<JournalRecord>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum JournalHostErrorKind {
    Unavailable,
    CorruptData,
    Cancelled,
    Other,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum JournalHostError {
    #[error("journal host failure ({kind:?}): {diagnostic}")]
    Failed {
        kind: JournalHostErrorKind,
        diagnostic: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendRequest {
    pub operation_id: String,
    pub destination: String,
    pub amount_nanograms: String,
    pub secret_ref: ProtectedSecretRef,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Enum)]
#[serde(rename_all = "camelCase")]
pub enum SendPhase {
    Idle,
    Validating,
    Authorizing,
    Preparing,
    Persisting,
    ReadyToSubmit,
    Submitting,
    SubmissionUnknown,
    Submitted,
    Failed,
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendSnapshot {
    pub operation_id: Option<String>,
    pub phase: SendPhase,
    pub error_message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct PreparedSend {
    pub operation_id: String,
    pub valid_until: u64,
    pub destination: String,
    pub amount_nanograms: String,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct SendResult {
    pub operation_id: String,
    pub message_hash: String,
    pub phase: SendPhase,
}
