use std::sync::Arc;

use crate::domain::{
    NetworkV3, ProtectedSecretHostErrorKindV3, ProtectedSecretHostErrorV3, ProtectedSecretReadV3,
    ProtectedSecretRefV3, ProtectedSecretStoreV3, SecretAccessReasonV3,
};
use crate::engine::WalletPlatformHostV3;
use crate::wallet_crypto::{derive_v5r1_address, generate_mnemonic};

const MNEMONIC_WORD_COUNT: usize = 24;
const MAX_WALLET_ID_BYTES: usize = 128;
const MAX_SECRET_REF_BYTES: usize = 256;
const MAX_HOST_DIAGNOSTIC_BYTES: usize = 256;

/// Public, persistable wallet metadata. Recovery words never belong here.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct WalletDescriptorV3 {
    pub wallet_id: String,
    pub address: String,
    pub network: NetworkV3,
    pub secret_ref: ProtectedSecretRefV3,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct CreateWalletRequestV3 {
    /// Stable application identity, normally a UUID generated by the host.
    pub wallet_id: String,
    pub network: NetworkV3,
}

/// A secret-bearing one-shot command. It must never be persisted or logged.
///
/// The words cross FFI because the user has to enter them. Rust validates and
/// derives the wallet; the host only provides protected storage.
#[derive(Clone, PartialEq, Eq, uniffi::Record)]
pub struct ImportWalletRequestV3 {
    pub wallet_id: String,
    pub network: NetworkV3,
    pub recovery_words: Vec<String>,
}

/// A deliberately one-shot presentation value, not wallet state.
///
/// The UI should discard this value as soon as the recovery-phrase screen is
/// dismissed. Neither `WalletDescriptorV3` nor `WalletSnapshotV3` contains it.
#[derive(Clone, PartialEq, Eq, uniffi::Record)]
pub struct RecoveryPhraseV3 {
    pub words: Vec<String>,
}

/// Result of creating a wallet. The descriptor is safe to persist; the
/// recovery phrase is transient and exists only so it can be shown once.
#[derive(Clone, PartialEq, Eq, uniffi::Record)]
pub struct CreatedWalletV3 {
    pub descriptor: WalletDescriptorV3,
    pub recovery_phrase: RecoveryPhraseV3,
}

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error, uniffi::Error)]
pub enum WalletLifecycleErrorV3 {
    #[error("invalid wallet identifier")]
    InvalidWalletId,
    #[error("invalid recovery phrase")]
    InvalidRecoveryPhrase,
    #[error("wallet address derivation failed")]
    AddressDerivationFailed,
    #[error("protected recovery phrase does not belong to this wallet")]
    SecretWalletMismatch,
    #[error("protected-secret host failure ({kind:?}): {message}")]
    ProtectedSecretHost {
        kind: ProtectedSecretHostErrorKindV3,
        message: String,
    },
}

impl From<ProtectedSecretHostErrorV3> for WalletLifecycleErrorV3 {
    fn from(value: ProtectedSecretHostErrorV3) -> Self {
        match value {
            ProtectedSecretHostErrorV3::Failed { kind, message } => Self::ProtectedSecretHost {
                kind,
                message: sanitize_diagnostic(&message),
            },
        }
    }
}

/// Coordinates wallet creation and recovery-phrase access.
///
/// It intentionally has no stream, refresh, reconciliation, or journal API.
/// Public wallet metadata remains owned by the embedding application; this
/// object owns the boundary between Rust key derivation and protected storage.
#[derive(uniffi::Object)]
pub struct WalletLifecycleV3 {
    platform_host: Arc<dyn WalletPlatformHostV3>,
}

#[uniffi::export]
impl WalletLifecycleV3 {
    #[uniffi::constructor]
    pub fn new(platform_host: Arc<dyn WalletPlatformHostV3>) -> Arc<Self> {
        Arc::new(Self { platform_host })
    }

    /// Generates and derives a V5R1 wallet entirely in Rust, then stores the
    /// mnemonic through the host before returning persistable metadata.
    pub async fn create_wallet(
        &self,
        request: CreateWalletRequestV3,
    ) -> Result<CreatedWalletV3, WalletLifecycleErrorV3> {
        validate_wallet_id(&request.wallet_id)?;

        let mnemonic =
            generate_mnemonic().map_err(|_| WalletLifecycleErrorV3::InvalidRecoveryPhrase)?;
        let secret = SensitiveMnemonicV3::from_generated(mnemonic)?;
        let descriptor = derive_descriptor(&request.wallet_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        let recovery_phrase = secret.presentation()?;

        Ok(CreatedWalletV3 {
            descriptor,
            recovery_phrase,
        })
    }

    /// Validates an entered mnemonic and imports it as a V5R1 wallet. The
    /// phrase is not returned because the user already supplied it.
    pub async fn import_wallet(
        &self,
        request: ImportWalletRequestV3,
    ) -> Result<WalletDescriptorV3, WalletLifecycleErrorV3> {
        validate_wallet_id(&request.wallet_id)?;

        let secret = SensitiveMnemonicV3::from_words(request.recovery_words)?;
        let descriptor = derive_descriptor(&request.wallet_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        Ok(descriptor)
    }

    /// Authenticates through the host, verifies that the returned secret still
    /// derives the expected address, and exposes a transient presentation.
    pub async fn reveal_recovery_phrase(
        &self,
        descriptor: WalletDescriptorV3,
    ) -> Result<RecoveryPhraseV3, WalletLifecycleErrorV3> {
        validate_descriptor(&descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretReadV3 {
                secret_ref: descriptor.secret_ref.clone(),
                reason: SecretAccessReasonV3::RevealRecoveryPhrase,
                prompt: "Authenticate to reveal this wallet's recovery phrase".to_owned(),
            })
            .await?;
        let secret = SensitiveMnemonicV3::from_bytes(bytes)?;
        let actual = derive_address(descriptor.network, &secret)?;
        if actual != descriptor.address {
            return Err(WalletLifecycleErrorV3::SecretWalletMismatch);
        }

        secret.presentation()
    }

    /// Deletes only the protected secret. The embedding application should
    /// remove its non-secret `WalletDescriptorV3` after this call succeeds.
    pub async fn delete_wallet(
        &self,
        descriptor: WalletDescriptorV3,
    ) -> Result<(), WalletLifecycleErrorV3> {
        validate_descriptor(&descriptor)?;
        self.platform_host
            .delete_protected_secret(descriptor.secret_ref)
            .await
            .map_err(Into::into)
    }
}

impl WalletLifecycleV3 {
    async fn store(
        &self,
        secret_ref: &ProtectedSecretRefV3,
        bytes: &[u8],
    ) -> Result<(), WalletLifecycleErrorV3> {
        self.platform_host
            .store_protected_secret(ProtectedSecretStoreV3 {
                secret_ref: secret_ref.clone(),
                bytes: bytes.to_vec(),
                // This is an access-control requirement for subsequent reads,
                // not a request to prompt while creating the item.
                require_user_presence: true,
            })
            .await
            .map_err(Into::into)
    }
}

/// Secret memory owned by Rust while a lifecycle operation is in flight.
///
/// FFI and platform APIs can still make bounded transient copies. This type
/// guarantees only that the buffer retained by this Rust operation is wiped.
struct SensitiveMnemonicV3 {
    bytes: Vec<u8>,
}

impl SensitiveMnemonicV3 {
    fn from_generated(mnemonic: String) -> Result<Self, WalletLifecycleErrorV3> {
        Self::from_bytes(mnemonic.into_bytes())
    }

    fn from_words(words: Vec<String>) -> Result<Self, WalletLifecycleErrorV3> {
        if words.len() != MNEMONIC_WORD_COUNT {
            return Err(WalletLifecycleErrorV3::InvalidRecoveryPhrase);
        }

        let mut candidate = Self {
            bytes: Vec::with_capacity(words.iter().map(String::len).sum::<usize>() + 23),
        };
        for (index, word) in words.into_iter().enumerate() {
            if !valid_mnemonic_word(&word) {
                return Err(WalletLifecycleErrorV3::InvalidRecoveryPhrase);
            }
            if index != 0 {
                candidate.bytes.push(b' ');
            }
            candidate.bytes.extend_from_slice(word.as_bytes());
        }
        candidate.validate()?;
        Ok(candidate)
    }

    fn from_bytes(bytes: Vec<u8>) -> Result<Self, WalletLifecycleErrorV3> {
        let candidate = Self { bytes };
        candidate.validate()?;
        Ok(candidate)
    }

    fn validate(&self) -> Result<(), WalletLifecycleErrorV3> {
        let phrase = self.as_str()?;
        let words = phrase.split(' ').collect::<Vec<_>>();
        if words.len() != MNEMONIC_WORD_COUNT || words.iter().any(|word| !valid_mnemonic_word(word))
        {
            return Err(WalletLifecycleErrorV3::InvalidRecoveryPhrase);
        }
        Ok(())
    }

    fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    fn as_str(&self) -> Result<&str, WalletLifecycleErrorV3> {
        std::str::from_utf8(&self.bytes).map_err(|_| WalletLifecycleErrorV3::InvalidRecoveryPhrase)
    }

    fn presentation(&self) -> Result<RecoveryPhraseV3, WalletLifecycleErrorV3> {
        Ok(RecoveryPhraseV3 {
            words: self.as_str()?.split(' ').map(str::to_owned).collect(),
        })
    }
}

impl Drop for SensitiveMnemonicV3 {
    fn drop(&mut self) {
        self.bytes.fill(0);
    }
}

fn derive_descriptor(
    wallet_id: &str,
    network: NetworkV3,
    secret: &SensitiveMnemonicV3,
) -> Result<WalletDescriptorV3, WalletLifecycleErrorV3> {
    let secret_ref = secret_ref_for(wallet_id)?;
    Ok(WalletDescriptorV3 {
        wallet_id: wallet_id.to_owned(),
        address: derive_address(network, secret)?,
        network,
        secret_ref,
    })
}

fn derive_address(
    network: NetworkV3,
    secret: &SensitiveMnemonicV3,
) -> Result<String, WalletLifecycleErrorV3> {
    derive_v5r1_address(secret.as_str()?, network, false)
        .map_err(|_| WalletLifecycleErrorV3::AddressDerivationFailed)
}

fn secret_ref_for(wallet_id: &str) -> Result<ProtectedSecretRefV3, WalletLifecycleErrorV3> {
    validate_wallet_id(wallet_id)?;
    let value = format!("wallet-v3:{wallet_id}:mnemonic");
    if value.len() > MAX_SECRET_REF_BYTES {
        return Err(WalletLifecycleErrorV3::InvalidWalletId);
    }
    Ok(ProtectedSecretRefV3 { value })
}

fn validate_descriptor(descriptor: &WalletDescriptorV3) -> Result<(), WalletLifecycleErrorV3> {
    validate_wallet_id(&descriptor.wallet_id)?;
    if descriptor.secret_ref != secret_ref_for(&descriptor.wallet_id)?
        || descriptor.address.is_empty()
    {
        return Err(WalletLifecycleErrorV3::InvalidWalletId);
    }
    Ok(())
}

fn validate_wallet_id(wallet_id: &str) -> Result<(), WalletLifecycleErrorV3> {
    if wallet_id.is_empty()
        || wallet_id.len() > MAX_WALLET_ID_BYTES
        || !wallet_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err(WalletLifecycleErrorV3::InvalidWalletId);
    }
    Ok(())
}

fn valid_mnemonic_word(word: &str) -> bool {
    !word.is_empty()
        && word.len() <= 32
        && word
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() && byte.is_ascii_alphabetic())
}

fn sanitize_diagnostic(message: &str) -> String {
    let mut result = String::with_capacity(message.len().min(MAX_HOST_DIAGNOSTIC_BYTES));
    for character in message.chars() {
        if result.len() >= MAX_HOST_DIAGNOSTIC_BYTES {
            break;
        }
        result.push(if character.is_control() {
            ' '
        } else {
            character
        });
    }
    result
}
