use std::sync::Arc;

use crate::domain::{
    Network, ProtectedSecretHostError, ProtectedSecretHostErrorKind, ProtectedSecretRead,
    ProtectedSecretRef, ProtectedSecretStore, SecretAccessReason,
};
use crate::engine::WalletPlatformHost;
use crate::wallet_crypto::{derive_v5r1_address, generate_mnemonic};

const MNEMONIC_WORD_COUNT: usize = 24;
const MAX_WALLET_ID_BYTES: usize = 128;
const MAX_SECRET_REF_BYTES: usize = 256;
const MAX_HOST_DIAGNOSTIC_BYTES: usize = 256;

/// Public, persistable wallet metadata. Recovery words never belong here.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct WalletDescriptor {
    pub wallet_id: String,
    pub address: String,
    pub network: Network,
    pub secret_ref: ProtectedSecretRef,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreateWalletRequest {
    /// Stable application identity, normally a UUID generated by the host.
    pub wallet_id: String,
    pub network: Network,
}

/// A secret-bearing one-shot command. It must never be persisted or logged.
///
/// The words cross FFI because the user has to enter them. Rust validates and
/// derives the wallet; the host only provides protected storage.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct ImportWalletRequest {
    pub wallet_id: String,
    pub network: Network,
    pub recovery_words: Vec<String>,
}

/// A deliberately one-shot presentation value, not wallet state.
///
/// The UI should discard this value as soon as the recovery-phrase screen is
/// dismissed. Neither `WalletDescriptor` nor `WalletSnapshot` contains it.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct RecoveryPhrase {
    pub words: Vec<String>,
}

/// Result of creating a wallet. The descriptor is safe to persist; the
/// recovery phrase is transient and exists only so it can be shown once.
#[derive(Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize, uniffi::Record)]
#[serde(rename_all = "camelCase")]
pub struct CreatedWallet {
    pub descriptor: WalletDescriptor,
    pub recovery_phrase: RecoveryPhrase,
}

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    serde::Serialize,
    serde::Deserialize,
    uniffi::Error,
)]
#[serde(rename_all = "camelCase")]
pub enum WalletLifecycleError {
    #[error("invalid wallet identifier")]
    InvalidWalletId,
    #[error("invalid recovery phrase")]
    InvalidRecoveryPhrase,
    #[error("wallet address derivation failed")]
    AddressDerivationFailed,
    #[error("protected recovery phrase does not belong to this wallet")]
    SecretWalletMismatch,
    #[error("protected-secret host failure ({kind:?}): {diagnostic}")]
    ProtectedSecretHost {
        kind: ProtectedSecretHostErrorKind,
        diagnostic: String,
    },
}

impl From<ProtectedSecretHostError> for WalletLifecycleError {
    fn from(value: ProtectedSecretHostError) -> Self {
        match value {
            ProtectedSecretHostError::Failed { kind, diagnostic } => Self::ProtectedSecretHost {
                kind,
                diagnostic: sanitize_diagnostic(&diagnostic),
            },
        }
    }
}

/// Coordinates wallet creation and recovery-phrase access.
///
/// It intentionally has no stream, refresh, reconciliation, or journal API.
/// Public wallet metadata remains owned by the embedding application; this
/// object owns the boundary between Rust key derivation and protected storage.
#[derive(uniffi::Object)]
pub struct WalletLifecycle {
    platform_host: Arc<dyn WalletPlatformHost>,
}

#[uniffi::export]
impl WalletLifecycle {
    #[uniffi::constructor]
    pub fn new(platform_host: Arc<dyn WalletPlatformHost>) -> Arc<Self> {
        Arc::new(Self { platform_host })
    }

    /// Generates and derives a V5R1 wallet entirely in Rust, then stores the
    /// mnemonic through the host before returning persistable metadata.
    pub async fn create_wallet(
        &self,
        request: CreateWalletRequest,
    ) -> Result<CreatedWallet, WalletLifecycleError> {
        validate_wallet_id(&request.wallet_id)?;

        let mnemonic =
            generate_mnemonic().map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)?;
        let secret = SensitiveMnemonic::from_generated(mnemonic)?;
        let descriptor = derive_descriptor(&request.wallet_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        let recovery_phrase = secret.presentation()?;

        Ok(CreatedWallet {
            descriptor,
            recovery_phrase,
        })
    }

    /// Validates an entered mnemonic and imports it as a V5R1 wallet. The
    /// phrase is not returned because the user already supplied it.
    pub async fn import_wallet(
        &self,
        request: ImportWalletRequest,
    ) -> Result<WalletDescriptor, WalletLifecycleError> {
        validate_wallet_id(&request.wallet_id)?;

        let secret = SensitiveMnemonic::from_words(request.recovery_words)?;
        let descriptor = derive_descriptor(&request.wallet_id, request.network, &secret)?;

        self.store(&descriptor.secret_ref, secret.as_bytes())
            .await?;
        Ok(descriptor)
    }

    /// Authenticates through the host, verifies that the returned secret still
    /// derives the expected address, and exposes a transient presentation.
    pub async fn reveal_recovery_phrase(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<RecoveryPhrase, WalletLifecycleError> {
        validate_descriptor(&descriptor)?;

        let bytes = self
            .platform_host
            .read_protected_secret(ProtectedSecretRead {
                secret_ref: descriptor.secret_ref.clone(),
                reason: SecretAccessReason::RevealRecoveryPhrase,
                prompt: "Authenticate to reveal this wallet's recovery phrase".to_owned(),
            })
            .await?;
        let secret = SensitiveMnemonic::from_bytes(bytes)?;
        let actual = derive_address(descriptor.network, &secret)?;
        if actual != descriptor.address {
            return Err(WalletLifecycleError::SecretWalletMismatch);
        }

        secret.presentation()
    }

    /// Deletes only the protected secret. The embedding application should
    /// remove its non-secret `WalletDescriptor` after this call succeeds.
    pub async fn delete_wallet(
        &self,
        descriptor: WalletDescriptor,
    ) -> Result<(), WalletLifecycleError> {
        validate_descriptor(&descriptor)?;
        self.platform_host
            .delete_protected_secret(descriptor.secret_ref)
            .await
            .map_err(Into::into)
    }
}

impl WalletLifecycle {
    async fn store(
        &self,
        secret_ref: &ProtectedSecretRef,
        bytes: &[u8],
    ) -> Result<(), WalletLifecycleError> {
        self.platform_host
            .store_protected_secret(ProtectedSecretStore {
                secret_ref: secret_ref.clone(),
                bytes: bytes.to_vec(),
                // This is an access-control requirement for subsequent reads,
                // not a request to prompt while creating the item.
                require_user_presence: true,
            })
            .await
            .map_err(Into::into)
    }
}

/// Secret memory owned by Rust while a lifecycle operation is in flight.
///
/// FFI and platform APIs can still make bounded transient copies. This type
/// guarantees only that the buffer retained by this Rust operation is wiped.
struct SensitiveMnemonic {
    bytes: Vec<u8>,
}

impl SensitiveMnemonic {
    fn from_generated(mnemonic: String) -> Result<Self, WalletLifecycleError> {
        Self::from_bytes(mnemonic.into_bytes())
    }

    fn from_words(words: Vec<String>) -> Result<Self, WalletLifecycleError> {
        if words.len() != MNEMONIC_WORD_COUNT {
            return Err(WalletLifecycleError::InvalidRecoveryPhrase);
        }

        let mut candidate = Self {
            bytes: Vec::with_capacity(words.iter().map(String::len).sum::<usize>() + 23),
        };
        for (index, word) in words.into_iter().enumerate() {
            if !valid_mnemonic_word(&word) {
                return Err(WalletLifecycleError::InvalidRecoveryPhrase);
            }
            if index != 0 {
                candidate.bytes.push(b' ');
            }
            candidate.bytes.extend_from_slice(word.as_bytes());
        }
        candidate.validate()?;
        Ok(candidate)
    }

    fn from_bytes(bytes: Vec<u8>) -> Result<Self, WalletLifecycleError> {
        let candidate = Self { bytes };
        candidate.validate()?;
        Ok(candidate)
    }

    fn validate(&self) -> Result<(), WalletLifecycleError> {
        let phrase = self.as_str()?;
        let words = phrase.split(' ').collect::<Vec<_>>();
        if words.len() != MNEMONIC_WORD_COUNT || words.iter().any(|word| !valid_mnemonic_word(word))
        {
            return Err(WalletLifecycleError::InvalidRecoveryPhrase);
        }
        Ok(())
    }

    fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    fn as_str(&self) -> Result<&str, WalletLifecycleError> {
        std::str::from_utf8(&self.bytes).map_err(|_| WalletLifecycleError::InvalidRecoveryPhrase)
    }

    fn presentation(&self) -> Result<RecoveryPhrase, WalletLifecycleError> {
        Ok(RecoveryPhrase {
            words: self.as_str()?.split(' ').map(str::to_owned).collect(),
        })
    }
}

impl Drop for SensitiveMnemonic {
    fn drop(&mut self) {
        self.bytes.fill(0);
    }
}

fn derive_descriptor(
    wallet_id: &str,
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<WalletDescriptor, WalletLifecycleError> {
    let secret_ref = secret_ref_for(wallet_id)?;
    Ok(WalletDescriptor {
        wallet_id: wallet_id.to_owned(),
        address: derive_address(network, secret)?,
        network,
        secret_ref,
    })
}

fn derive_address(
    network: Network,
    secret: &SensitiveMnemonic,
) -> Result<String, WalletLifecycleError> {
    derive_v5r1_address(secret.as_str()?, network, false)
        .map_err(|_| WalletLifecycleError::AddressDerivationFailed)
}

fn secret_ref_for(wallet_id: &str) -> Result<ProtectedSecretRef, WalletLifecycleError> {
    validate_wallet_id(wallet_id)?;
    let value = format!("wallet:{wallet_id}:mnemonic");
    if value.len() > MAX_SECRET_REF_BYTES {
        return Err(WalletLifecycleError::InvalidWalletId);
    }
    Ok(ProtectedSecretRef { value })
}

fn validate_descriptor(descriptor: &WalletDescriptor) -> Result<(), WalletLifecycleError> {
    validate_wallet_id(&descriptor.wallet_id)?;
    if descriptor.secret_ref != secret_ref_for(&descriptor.wallet_id)?
        || descriptor.address.is_empty()
    {
        return Err(WalletLifecycleError::InvalidWalletId);
    }
    Ok(())
}

fn validate_wallet_id(wallet_id: &str) -> Result<(), WalletLifecycleError> {
    if wallet_id.is_empty()
        || wallet_id.len() > MAX_WALLET_ID_BYTES
        || !wallet_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
    {
        return Err(WalletLifecycleError::InvalidWalletId);
    }
    Ok(())
}

fn valid_mnemonic_word(word: &str) -> bool {
    !word.is_empty()
        && word.len() <= 32
        && word
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() && byte.is_ascii_alphabetic())
}

fn sanitize_diagnostic(message: &str) -> String {
    let mut result = String::with_capacity(message.len().min(MAX_HOST_DIAGNOSTIC_BYTES));
    for character in message.chars() {
        if result.len() >= MAX_HOST_DIAGNOSTIC_BYTES {
            break;
        }
        result.push(if character.is_control() {
            ' '
        } else {
            character
        });
    }
    result
}
